const fs = require('fs');
const path = require('path');

const currentSquads = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/squads.json'), 'utf8'));

const badSquads = [
  // --- PREMIER LEAGUE DISASTERS ---
  {
    id: "derby-county-2007-08",
    clubName: "Derby County",
    year: "2007-08",
    fullName: "Derby County 2007-08 (Record 11 Pts)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#000000",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "der08-miller",
        name: "Kenny Miller",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Scotland",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 82,
        shooting: 75,
        passing: 68,
        dribbling: 74,
        defending: 38,
        physical: 76,
        composure: 75
      },
      {
        id: "der08-savage",
        name: "Robbie Savage",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Wales",
        league: "Premier League",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 68,
        shooting: 68,
        passing: 74,
        dribbling: 70,
        defending: 78,
        physical: 82,
        composure: 74,
        auraTrait: {
          id: "savage-shithousery",
          name: "The Wind-Up Merchant",
          description: "+30% foul-drawing rate; opposing playmaker loses 10% composure.",
          shortDesc: "+30% foul drawing",
          rarity: "Rare"
        }
      },
      {
        id: "der08-barnes",
        name: "Giles Barnes",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "England",
        league: "Premier League",
        position: "MID",
        specificPosition: "CAM",
        overall: 75,
        pace: 84,
        shooting: 72,
        passing: 73,
        dribbling: 79,
        defending: 40,
        physical: 70,
        composure: 73
      },
      {
        id: "der08-villa",
        name: "Emanuel Villa",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Argentina",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 73,
        pace: 74,
        shooting: 74,
        passing: 62,
        dribbling: 70,
        defending: 32,
        physical: 78,
        composure: 72
      },
      {
        id: "der08-pearson",
        name: "Stephen Pearson",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Scotland",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 72,
        pace: 76,
        shooting: 66,
        passing: 72,
        dribbling: 71,
        defending: 68,
        physical: 74,
        composure: 71
      },
      {
        id: "der08-sterjovski",
        name: "Mile Sterjovski",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Australia",
        league: "Premier League",
        position: "MID",
        specificPosition: "RM",
        overall: 72,
        pace: 75,
        shooting: 70,
        passing: 71,
        dribbling: 73,
        defending: 50,
        physical: 70,
        composure: 72
      },
      {
        id: "der08-moore",
        name: "Darren Moore",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Jamaica",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 56,
        shooting: 30,
        passing: 58,
        dribbling: 52,
        defending: 78,
        physical: 88,
        composure: 75
      },
      {
        id: "der08-davis",
        name: "Claude Davis",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Jamaica",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 71,
        pace: 64,
        shooting: 28,
        passing: 54,
        dribbling: 50,
        defending: 75,
        physical: 82,
        composure: 68
      },
      {
        id: "der08-mears",
        name: "Tyrone Mears",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 73,
        pace: 84,
        shooting: 50,
        passing: 68,
        dribbling: 71,
        defending: 72,
        physical: 74,
        composure: 70
      },
      {
        id: "der08-mceveley",
        name: "Jay McEveley",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Scotland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "LB",
        overall: 71,
        pace: 74,
        shooting: 46,
        passing: 65,
        dribbling: 66,
        defending: 72,
        physical: 75,
        composure: 68
      },
      {
        id: "der08-carroll",
        name: "Roy Carroll",
        clubYear: "Derby County 2007-08",
        clubName: "Derby County",
        year: "2007-08",
        country: "Northern Ireland",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 73,
        pace: 50,
        shooting: 20,
        passing: 64,
        dribbling: 45,
        defending: 76,
        physical: 74,
        composure: 70
      }
    ]
  },
  {
    id: "sunderland-2016-17",
    clubName: "Sunderland",
    year: "2016-17",
    fullName: "Sunderland 2016-17 (Moyes Relegation)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#EB172B",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "sun17-defoe",
        name: "Jermain Defoe",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "England",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 82,
        pace: 82,
        shooting: 87,
        passing: 70,
        dribbling: 81,
        defending: 32,
        physical: 70,
        composure: 89,
        auraTrait: {
          id: "defoe-sniping",
          name: "One-Man Resurrect",
          description: "+35% conversion rate on rare counter opportunities.",
          shortDesc: "+35% isolated strike",
          rarity: "Epic"
        }
      },
      {
        id: "sun17-borini",
        name: "Fabio Borini",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "Italy",
        league: "Premier League",
        position: "FWD",
        specificPosition: "RW",
        overall: 75,
        pace: 80,
        shooting: 75,
        passing: 69,
        dribbling: 76,
        defending: 48,
        physical: 74,
        composure: 75
      },
      {
        id: "sun17-watmore",
        name: "Duncan Watmore",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "England",
        league: "Premier League",
        position: "FWD",
        specificPosition: "LW",
        overall: 73,
        pace: 85,
        shooting: 70,
        passing: 66,
        dribbling: 75,
        defending: 44,
        physical: 70,
        composure: 71
      },
      {
        id: "sun17-rodwell",
        name: "Jack Rodwell",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "England",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 73,
        pace: 70,
        shooting: 68,
        passing: 74,
        dribbling: 72,
        defending: 74,
        physical: 78,
        composure: 72
      },
      {
        id: "sun17-larsson",
        name: "Sebastian Larsson",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "Sweden",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 75,
        pace: 68,
        shooting: 75,
        passing: 79,
        dribbling: 73,
        defending: 68,
        physical: 72,
        composure: 78
      },
      {
        id: "sun17-pienaar",
        name: "Steven Pienaar",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "South Africa",
        league: "Premier League",
        position: "MID",
        specificPosition: "CAM",
        overall: 74,
        pace: 68,
        shooting: 69,
        passing: 78,
        dribbling: 77,
        defending: 55,
        physical: 65,
        composure: 79
      },
      {
        id: "sun17-kone",
        name: "Lamine Kone",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "Ivory Coast",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 71,
        shooting: 32,
        passing: 60,
        dribbling: 58,
        defending: 78,
        physical: 86,
        composure: 74
      },
      {
        id: "sun17-oshea",
        name: "John O'Shea",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "Ireland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 74,
        pace: 54,
        shooting: 45,
        passing: 66,
        dribbling: 60,
        defending: 77,
        physical: 76,
        composure: 82
      },
      {
        id: "sun17-jones",
        name: "Billy Jones",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 72,
        pace: 74,
        shooting: 48,
        passing: 68,
        dribbling: 69,
        defending: 73,
        physical: 75,
        composure: 70
      },
      {
        id: "sun17-van-aanholt",
        name: "Patrick van Aanholt",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "Netherlands",
        league: "Premier League",
        position: "DEF",
        specificPosition: "LB",
        overall: 76,
        pace: 88,
        shooting: 68,
        passing: 72,
        dribbling: 77,
        defending: 73,
        physical: 72,
        composure: 74
      },
      {
        id: "sun17-pickford",
        name: "Jordan Pickford",
        clubYear: "Sunderland 2016-17",
        clubName: "Sunderland",
        year: "2016-17",
        country: "England",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 79,
        pace: 58,
        shooting: 25,
        passing: 84,
        dribbling: 50,
        defending: 81,
        physical: 76,
        composure: 80
      }
    ]
  },
  {
    id: "qpr-2012-13",
    clubName: "Queens Park Rangers",
    year: "2012-13",
    fullName: "QPR 2012-13 (Chaotic Relegation)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#005CAB",
    accentColor: "#FFFFFF",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "qpr13-taarabt",
        name: "Adel Taarabt",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Morocco",
        league: "Premier League",
        position: "MID",
        specificPosition: "CAM",
        overall: 80,
        pace: 82,
        shooting: 81,
        passing: 84,
        dribbling: 91,
        defending: 30,
        physical: 74,
        composure: 82,
        auraTrait: {
          id: "taarabt-nutmeg",
          name: "Loftus Road Nutmeg",
          description: "+40% dribble success but 10% chance to lose ball in own half.",
          shortDesc: "+40% pure street flair",
          rarity: "Epic"
        }
      },
      {
        id: "qpr13-remy",
        name: "Loic Remy",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "France",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 79,
        pace: 91,
        shooting: 80,
        passing: 68,
        dribbling: 80,
        defending: 32,
        physical: 74,
        composure: 78
      },
      {
        id: "qpr13-swp",
        name: "Shaun Wright-Phillips",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "England",
        league: "Premier League",
        position: "FWD",
        specificPosition: "RW",
        overall: 75,
        pace: 86,
        shooting: 72,
        passing: 71,
        dribbling: 80,
        defending: 40,
        physical: 64,
        composure: 74
      },
      {
        id: "qpr13-park",
        name: "Park Ji-sung",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "South Korea",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 77,
        pace: 75,
        shooting: 70,
        passing: 77,
        dribbling: 76,
        defending: 74,
        physical: 76,
        composure: 84
      },
      {
        id: "qpr13-granero",
        name: "Esteban Granero",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Spain",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 76,
        pace: 68,
        shooting: 74,
        passing: 81,
        dribbling: 77,
        defending: 68,
        physical: 72,
        composure: 78
      },
      {
        id: "qpr13-mbia",
        name: "Stephane Mbia",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Cameroon",
        league: "Premier League",
        position: "MID",
        specificPosition: "CDM",
        overall: 76,
        pace: 74,
        shooting: 64,
        passing: 72,
        dribbling: 72,
        defending: 80,
        physical: 86,
        composure: 74
      },
      {
        id: "qpr13-samba",
        name: "Christopher Samba",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Congo",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 60,
        shooting: 45,
        passing: 55,
        dribbling: 52,
        defending: 79,
        physical: 92,
        composure: 74
      },
      {
        id: "qpr13-hill",
        name: "Clint Hill",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 55,
        shooting: 35,
        passing: 60,
        dribbling: 54,
        defending: 76,
        physical: 82,
        composure: 76
      },
      {
        id: "qpr13-bosingwa",
        name: "Jose Bosingwa",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Portugal",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 75,
        pace: 82,
        shooting: 55,
        passing: 72,
        dribbling: 75,
        defending: 74,
        physical: 74,
        composure: 75
      },
      {
        id: "qpr13-traore",
        name: "Armand Traore",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Senegal",
        league: "Premier League",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 88,
        shooting: 52,
        passing: 68,
        dribbling: 76,
        defending: 71,
        physical: 74,
        composure: 70
      },
      {
        id: "qpr13-cesar",
        name: "Julio Cesar",
        clubYear: "QPR 2012-13",
        clubName: "Queens Park Rangers",
        year: "2012-13",
        country: "Brazil",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 81,
        pace: 54,
        shooting: 25,
        passing: 72,
        dribbling: 50,
        defending: 83,
        physical: 78,
        composure: 85
      }
    ]
  },
  // --- LA LIGA UNDERDOGS & RELEGATIONS ---
  {
    id: "cordoba-2014-15",
    clubName: "Cordoba",
    year: "2014-15",
    fullName: "Cordoba 2014-15 (20 Pts Last Place)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#008000",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "cor15-ghilas",
        name: "Nabil Ghilas",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Algeria",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 84,
        shooting: 76,
        passing: 65,
        dribbling: 76,
        defending: 35,
        physical: 80,
        composure: 73
      },
      {
        id: "cor15-bebe",
        name: "Bebe",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Portugal",
        league: "La Liga",
        position: "FWD",
        specificPosition: "LW",
        overall: 74,
        pace: 87,
        shooting: 78,
        passing: 68,
        dribbling: 78,
        defending: 38,
        physical: 82,
        composure: 71,
        auraTrait: {
          id: "bebe-cannon",
          name: "Uncontrolled Cannon",
          description: "+35% long range shot power; +15% conversion outside penalty box.",
          shortDesc: "+35% wild long shots",
          rarity: "Rare"
        }
      },
      {
        id: "cor15-cartabia",
        name: "Fede Cartabia",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Argentina",
        league: "La Liga",
        position: "MID",
        specificPosition: "RW",
        overall: 76,
        pace: 84,
        shooting: 73,
        passing: 76,
        dribbling: 83,
        defending: 36,
        physical: 62,
        composure: 75
      },
      {
        id: "cor15-khrin",
        name: "Rene Khrin",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Slovenia",
        league: "La Liga",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 68,
        shooting: 62,
        passing: 74,
        dribbling: 72,
        defending: 76,
        physical: 79,
        composure: 73
      },
      {
        id: "cor15-luso",
        name: "Luso Delgado",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 72,
        pace: 66,
        shooting: 60,
        passing: 72,
        dribbling: 69,
        defending: 74,
        physical: 76,
        composure: 72
      },
      {
        id: "cor15-andone",
        name: "Florin Andone",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Romania",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 74,
        pace: 82,
        shooting: 75,
        passing: 62,
        dribbling: 74,
        defending: 40,
        physical: 78,
        composure: 74
      },
      {
        id: "cor15-lopez",
        name: "Inigo Lopez",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 58,
        shooting: 32,
        passing: 58,
        dribbling: 52,
        defending: 76,
        physical: 82,
        composure: 72
      },
      {
        id: "cor15-pantic",
        name: "Aleksandar Pantic",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Serbia",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 68,
        shooting: 30,
        passing: 62,
        dribbling: 58,
        defending: 75,
        physical: 78,
        composure: 71
      },
      {
        id: "cor15-crespo",
        name: "Jose Angel Crespo",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 76,
        shooting: 45,
        passing: 68,
        dribbling: 69,
        defending: 75,
        physical: 76,
        composure: 73
      },
      {
        id: "cor15-edimar",
        name: "Edimar Fraga",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Brazil",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 72,
        pace: 78,
        shooting: 50,
        passing: 66,
        dribbling: 70,
        defending: 71,
        physical: 72,
        composure: 69
      },
      {
        id: "cor15-juancarlos",
        name: "Juan Carlos Martin",
        clubYear: "Cordoba 2014-15",
        clubName: "Cordoba",
        year: "2014-15",
        country: "Spain",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 73,
        pace: 52,
        shooting: 20,
        passing: 65,
        dribbling: 45,
        defending: 75,
        physical: 74,
        composure: 72
      }
    ]
  },
  {
    id: "elche-2022-23",
    clubName: "Elche",
    year: "2022-23",
    fullName: "Elche 2022-23 (La Liga 25 Pts)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#006400",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "elc23-boye",
        name: "Lucas Boye",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Argentina",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 78,
        pace: 76,
        shooting: 78,
        passing: 72,
        dribbling: 81,
        defending: 45,
        physical: 85,
        composure: 79
      },
      {
        id: "elc23-milla",
        name: "Pere Milla",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "FWD",
        specificPosition: "LW",
        overall: 76,
        pace: 78,
        shooting: 77,
        passing: 72,
        dribbling: 77,
        defending: 50,
        physical: 74,
        composure: 77
      },
      {
        id: "elc23-morente",
        name: "Tete Morente",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "RW",
        overall: 75,
        pace: 82,
        shooting: 72,
        passing: 73,
        dribbling: 78,
        defending: 52,
        physical: 74,
        composure: 74
      },
      {
        id: "elc23-fidel",
        name: "Fidel Chaves",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "LM",
        overall: 76,
        pace: 74,
        shooting: 74,
        passing: 79,
        dribbling: 78,
        defending: 58,
        physical: 70,
        composure: 78
      },
      {
        id: "elc23-gumbau",
        name: "Gerard Gumbau",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 76,
        pace: 68,
        shooting: 72,
        passing: 79,
        dribbling: 73,
        defending: 75,
        physical: 78,
        composure: 76
      },
      {
        id: "elc23-mascarell",
        name: "Omar Mascarell",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CDM",
        overall: 77,
        pace: 66,
        shooting: 60,
        passing: 78,
        dribbling: 74,
        defending: 80,
        physical: 82,
        composure: 78
      },
      {
        id: "elc23-bigas",
        name: "Pedro Bigas",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 75,
        pace: 68,
        shooting: 40,
        passing: 68,
        dribbling: 62,
        defending: 77,
        physical: 78,
        composure: 75
      },
      {
        id: "elc23-palacios",
        name: "Helibelton Palacios",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Colombia",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 74,
        pace: 78,
        shooting: 42,
        passing: 66,
        dribbling: 68,
        defending: 75,
        physical: 76,
        composure: 72
      },
      {
        id: "elc23-carmona",
        name: "Jose Angel Carmona",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 79,
        shooting: 55,
        passing: 70,
        dribbling: 72,
        defending: 74,
        physical: 76,
        composure: 72
      },
      {
        id: "elc23-clerc",
        name: "Carlos Clerc",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 80,
        shooting: 54,
        passing: 73,
        dribbling: 74,
        defending: 73,
        physical: 74,
        composure: 73
      },
      {
        id: "elc23-badia",
        name: "Edgar Badia",
        clubYear: "Elche 2022-23",
        clubName: "Elche",
        year: "2022-23",
        country: "Spain",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 78,
        pace: 56,
        shooting: 22,
        passing: 72,
        dribbling: 52,
        defending: 81,
        physical: 74,
        composure: 80,
        auraTrait: {
          id: "badia-barrage",
          name: "Point-Blank Reflex",
          description: "+25% save rate on shots inside the penalty box under heavy siege.",
          shortDesc: "+25% box saves",
          rarity: "Rare"
        }
      }
    ]
  },
  {
    id: "granada-2016-17",
    clubName: "Granada",
    year: "2016-17",
    fullName: "Granada 2016-17 (Tony Adams Relegation)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#A6192E",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "gra17-kravets",
        name: "Artem Kravets",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Ukraine",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 78,
        shooting: 77,
        passing: 65,
        dribbling: 73,
        defending: 36,
        physical: 79,
        composure: 74
      },
      {
        id: "gra17-pereira",
        name: "Andreas Pereira",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Brazil",
        league: "La Liga",
        position: "MID",
        specificPosition: "CAM",
        overall: 76,
        pace: 79,
        shooting: 75,
        passing: 80,
        dribbling: 82,
        defending: 52,
        physical: 68,
        composure: 76
      },
      {
        id: "gra17-boga",
        name: "Jeremie Boga",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Ivory Coast",
        league: "La Liga",
        position: "FWD",
        specificPosition: "LW",
        overall: 75,
        pace: 88,
        shooting: 70,
        passing: 70,
        dribbling: 84,
        defending: 35,
        physical: 66,
        composure: 72
      },
      {
        id: "gra17-carcela",
        name: "Mehdi Carcela",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Morocco",
        league: "La Liga",
        position: "MID",
        specificPosition: "RW",
        overall: 76,
        pace: 84,
        shooting: 74,
        passing: 74,
        dribbling: 83,
        defending: 40,
        physical: 66,
        composure: 74
      },
      {
        id: "gra17-wakaso",
        name: "Mubarak Wakaso",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Ghana",
        league: "La Liga",
        position: "MID",
        specificPosition: "CDM",
        overall: 76,
        pace: 79,
        shooting: 72,
        passing: 74,
        dribbling: 75,
        defending: 78,
        physical: 84,
        composure: 72
      },
      {
        id: "gra17-krjin",
        name: "Rene Krhin",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Slovenia",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 74,
        pace: 68,
        shooting: 60,
        passing: 75,
        dribbling: 72,
        defending: 76,
        physical: 78,
        composure: 73
      },
      {
        id: "gra17-ingason",
        name: "Sverrir Ingason",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Iceland",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 75,
        pace: 66,
        shooting: 35,
        passing: 62,
        dribbling: 56,
        defending: 78,
        physical: 84,
        composure: 74
      },
      {
        id: "gra17-lomban",
        name: "David Lomban",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 62,
        shooting: 40,
        passing: 65,
        dribbling: 56,
        defending: 75,
        physical: 78,
        composure: 74
      },
      {
        id: "gra17-foulquier",
        name: "Dimitri Foulquier",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "France",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 75,
        pace: 83,
        shooting: 48,
        passing: 68,
        dribbling: 72,
        defending: 76,
        physical: 81,
        composure: 72
      },
      {
        id: "gra17-silva",
        name: "Gaston Silva",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Uruguay",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 75,
        shooting: 48,
        passing: 69,
        dribbling: 68,
        defending: 75,
        physical: 76,
        composure: 73
      },
      {
        id: "gra17-ochoa",
        name: "Guillermo Ochoa",
        clubYear: "Granada 2016-17",
        clubName: "Granada",
        year: "2016-17",
        country: "Mexico",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 78,
        pace: 60,
        shooting: 25,
        passing: 70,
        dribbling: 50,
        defending: 82,
        physical: 75,
        composure: 82,
        auraTrait: {
          id: "ochoa-162-saves",
          name: "162-Save Sentry",
          description: "+30% reflex saves when facing 6+ shots on target.",
          shortDesc: "+30% high-volume saves",
          rarity: "Epic"
        }
      }
    ]
  },
  // --- SERIE A STRUGGLERS ---
  {
    id: "benevento-2017-18",
    clubName: "Benevento",
    year: "2017-18",
    fullName: "Benevento 2017-18 (Cult Underdogs)",
    type: "club",
    league: "Serie A",
    countryCode: "ITA",
    badgeColor: "#FFE500",
    accentColor: "#CC0000",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "ben18-coda",
        name: "Massimo Coda",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 76,
        shooting: 77,
        passing: 68,
        dribbling: 74,
        defending: 36,
        physical: 82,
        composure: 76
      },
      {
        id: "ben18-diabate",
        name: "Cheick Diabate",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Mali",
        league: "Serie A",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 70,
        shooting: 79,
        passing: 60,
        dribbling: 70,
        defending: 34,
        physical: 90,
        composure: 78,
        auraTrait: {
          id: "diabate-brace",
          name: "Super-Sub Rampage",
          description: "+35% conversion in the second half when trailing.",
          shortDesc: "+35% second half sub xG",
          rarity: "Rare"
        }
      },
      {
        id: "ben18-djuricic",
        name: "Filip Djuricic",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Serbia",
        league: "Serie A",
        position: "MID",
        specificPosition: "CAM",
        overall: 76,
        pace: 80,
        shooting: 72,
        passing: 78,
        dribbling: 83,
        defending: 42,
        physical: 66,
        composure: 77
      },
      {
        id: "ben18-sandro",
        name: "Sandro Ranieri",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Brazil",
        league: "Serie A",
        position: "MID",
        specificPosition: "CDM",
        overall: 76,
        pace: 68,
        shooting: 68,
        passing: 74,
        dribbling: 72,
        defending: 80,
        physical: 84,
        composure: 78
      },
      {
        id: "ben18-viola",
        name: "Nicolas Viola",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "MID",
        specificPosition: "CM",
        overall: 75,
        pace: 70,
        shooting: 75,
        passing: 79,
        dribbling: 75,
        defending: 68,
        physical: 72,
        composure: 76
      },
      {
        id: "ben18-cataldi",
        name: "Danilo Cataldi",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "MID",
        specificPosition: "CM",
        overall: 75,
        pace: 74,
        shooting: 70,
        passing: 78,
        dribbling: 76,
        defending: 72,
        physical: 74,
        composure: 76
      },
      {
        id: "ben18-djimsiti",
        name: "Berat Djimsiti",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Albania",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 70,
        shooting: 30,
        passing: 64,
        dribbling: 60,
        defending: 79,
        physical: 83,
        composure: 75
      },
      {
        id: "ben18-costa",
        name: "Andrea Costa",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 62,
        shooting: 38,
        passing: 62,
        dribbling: 56,
        defending: 76,
        physical: 78,
        composure: 73
      },
      {
        id: "ben18-sagna",
        name: "Bacary Sagna",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "France",
        league: "Serie A",
        position: "DEF",
        specificPosition: "RB",
        overall: 75,
        pace: 74,
        shooting: 52,
        passing: 72,
        dribbling: 71,
        defending: 78,
        physical: 76,
        composure: 82
      },
      {
        id: "ben18-letizia",
        name: "Gaetano Letizia",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 82,
        shooting: 56,
        passing: 70,
        dribbling: 74,
        defending: 73,
        physical: 72,
        composure: 73
      },
      {
        id: "ben18-brignoli",
        name: "Alberto Brignoli",
        clubYear: "Benevento 2017-18",
        clubName: "Benevento",
        year: "2017-18",
        country: "Italy",
        league: "Serie A",
        position: "GK",
        specificPosition: "GK",
        overall: 74,
        pace: 55,
        shooting: 45,
        passing: 68,
        dribbling: 48,
        defending: 77,
        physical: 75,
        composure: 80,
        auraTrait: {
          id: "brignoli-milan-header",
          name: "95th Min Goalkeeper Header",
          description: "+50% chance for goalkeeper to score on injury time corners when trailing by 1.",
          shortDesc: "+50% GK corner header goal",
          rarity: "Legendary"
        }
      }
    ]
  },
  // --- BUNDESLIGA STRUGGLERS ---
  {
    id: "schalke-2020-21",
    clubName: "Schalke 04",
    year: "2020-21",
    fullName: "Schalke 04 2020-21 (16 Pts Disaster)",
    type: "club",
    league: "Bundesliga",
    countryCode: "GER",
    badgeColor: "#004D9D",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "s04-huntelaar",
        name: "Klaas-Jan Huntelaar",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Netherlands",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 64,
        shooting: 82,
        passing: 66,
        dribbling: 70,
        defending: 35,
        physical: 76,
        composure: 86
      },
      {
        id: "s04-hoppe",
        name: "Matthew Hoppe",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "United States",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 74,
        pace: 80,
        shooting: 75,
        passing: 62,
        dribbling: 74,
        defending: 38,
        physical: 76,
        composure: 73
      },
      {
        id: "s04-harit",
        name: "Amine Harit",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Morocco",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CAM",
        overall: 78,
        pace: 84,
        shooting: 72,
        passing: 80,
        dribbling: 87,
        defending: 45,
        physical: 65,
        composure: 78
      },
      {
        id: "s04-serdar",
        name: "Suat Serdar",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Germany",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CM",
        overall: 77,
        pace: 78,
        shooting: 74,
        passing: 77,
        dribbling: 80,
        defending: 74,
        physical: 79,
        composure: 76
      },
      {
        id: "s04-mascarell",
        name: "Omar Mascarell",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Spain",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CDM",
        overall: 76,
        pace: 68,
        shooting: 60,
        passing: 76,
        dribbling: 73,
        defending: 79,
        physical: 81,
        composure: 77
      },
      {
        id: "s04-kolasinac",
        name: "Sead Kolasinac",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Bosnia and Herzegovina",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "LB",
        overall: 76,
        pace: 78,
        shooting: 64,
        passing: 72,
        dribbling: 73,
        defending: 76,
        physical: 88,
        composure: 76
      },
      {
        id: "s04-mustafi",
        name: "Shkodran Mustafi",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 75,
        pace: 64,
        shooting: 45,
        passing: 68,
        dribbling: 60,
        defending: 78,
        physical: 82,
        composure: 72
      },
      {
        id: "s04-thiaw",
        name: "Malick Thiaw",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 74,
        pace: 74,
        shooting: 35,
        passing: 66,
        dribbling: 62,
        defending: 76,
        physical: 83,
        composure: 74
      },
      {
        id: "s04-becker",
        name: "Timo Becker",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "RB",
        overall: 72,
        pace: 76,
        shooting: 46,
        passing: 65,
        dribbling: 66,
        defending: 72,
        physical: 76,
        composure: 70
      },
      {
        id: "s04-raman",
        name: "Benito Raman",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Belgium",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "RW",
        overall: 74,
        pace: 88,
        shooting: 73,
        passing: 67,
        dribbling: 76,
        defending: 40,
        physical: 68,
        composure: 72
      },
      {
        id: "s04-fahrmann",
        name: "Ralf Fahrmann",
        clubYear: "Schalke 04 2020-21",
        clubName: "Schalke 04",
        year: "2020-21",
        country: "Germany",
        league: "Bundesliga",
        position: "GK",
        specificPosition: "GK",
        overall: 76,
        pace: 52,
        shooting: 20,
        passing: 68,
        dribbling: 45,
        defending: 79,
        physical: 77,
        composure: 76
      }
    ]
  },
  // --- UNDERDOG INTERNATIONALS ---
  {
    id: "north-korea-2010",
    clubName: "North Korea",
    year: "2010",
    fullName: "North Korea 2010 (World Cup Underdogs)",
    type: "country",
    league: "International",
    countryCode: "PRK",
    badgeColor: "#ED1B2F",
    accentColor: "#024FA2",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "prk10-jong",
        name: "Jong Tae-se",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 78,
        shooting: 77,
        passing: 66,
        dribbling: 74,
        defending: 38,
        physical: 84,
        composure: 78,
        auraTrait: {
          id: "peoples-rooney",
          name: "People's Rooney Tears",
          description: "+30% physical hold-up play against powerhouse defenses.",
          shortDesc: "+30% hold-up physical",
          rarity: "Rare"
        }
      },
      {
        id: "prk10-hong",
        name: "Hong Yong-jo",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "FWD",
        specificPosition: "RW",
        overall: 74,
        pace: 82,
        shooting: 73,
        passing: 71,
        dribbling: 76,
        defending: 40,
        physical: 70,
        composure: 74
      },
      {
        id: "prk10-an",
        name: "An Yong-hak",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 70,
        shooting: 66,
        passing: 76,
        dribbling: 72,
        defending: 76,
        physical: 78,
        composure: 76
      },
      {
        id: "prk10-pak",
        name: "Pak Nam-chol",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 73,
        pace: 75,
        shooting: 68,
        passing: 74,
        dribbling: 73,
        defending: 70,
        physical: 74,
        composure: 72
      },
      {
        id: "prk10-mun",
        name: "Mun In-guk",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "MID",
        specificPosition: "RM",
        overall: 72,
        pace: 77,
        shooting: 66,
        passing: 72,
        dribbling: 73,
        defending: 64,
        physical: 70,
        composure: 70
      },
      {
        id: "prk10-ji",
        name: "Ji Yun-nam",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 73,
        pace: 80,
        shooting: 65,
        passing: 70,
        dribbling: 72,
        defending: 73,
        physical: 75,
        composure: 74,
        auraTrait: {
          id: "maracana-strike",
          name: "Gol Against Brazil",
          description: "+30% conversion on surprise overlapping box entries.",
          shortDesc: "+30% fullback box run",
          rarity: "Rare"
        }
      },
      {
        id: "prk10-ri-kwang",
        name: "Ri Kwang-chon",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 72,
        pace: 64,
        shooting: 30,
        passing: 60,
        dribbling: 54,
        defending: 75,
        physical: 80,
        composure: 72
      },
      {
        id: "prk10-pak-chol",
        name: "Pak Chol-jin",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 71,
        pace: 66,
        shooting: 28,
        passing: 58,
        dribbling: 52,
        defending: 74,
        physical: 78,
        composure: 70
      },
      {
        id: "prk10-cha",
        name: "Cha Jong-hyok",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 72,
        pace: 80,
        shooting: 46,
        passing: 67,
        dribbling: 69,
        defending: 73,
        physical: 74,
        composure: 70
      },
      {
        id: "prk10-choe",
        name: "Choe Kum-chol",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "FWD",
        specificPosition: "LW",
        overall: 71,
        pace: 76,
        shooting: 70,
        passing: 64,
        dribbling: 71,
        defending: 36,
        physical: 74,
        composure: 69
      },
      {
        id: "prk10-ri-myong",
        name: "Ri Myong-guk",
        clubYear: "North Korea 2010",
        clubName: "North Korea",
        year: "2010",
        country: "North Korea",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 73,
        pace: 54,
        shooting: 20,
        passing: 65,
        dribbling: 45,
        defending: 76,
        physical: 72,
        composure: 74
      }
    ]
  }
];

const existingIds = new Set(currentSquads.map(s => s.id));
const combined = [...currentSquads];

for (const bs of badSquads) {
  if (!existingIds.has(bs.id)) {
    combined.push(bs);
  }
}

const jsonOutput = JSON.stringify(combined, null, 2);
fs.writeFileSync(path.join(__dirname, '../src/data/squads.json'), jsonOutput, 'utf8');

const tsOutput = "import { SquadData } from '../types/football';\n\nexport const SQUADS: SquadData[] = " + jsonOutput + ";\n";
fs.writeFileSync(path.join(__dirname, '../src/data/squads.ts'), tsOutput, 'utf8');

console.log('Successfully appended underdog squads. Total squads now: ' + combined.length);
