const fs = require('fs');
const path = require('path');

const squadsJsonPath = path.join(__dirname, '../src/data/squads.json');
const squadsTsPath = path.join(__dirname, '../src/data/squads.ts');

const currentSquads = JSON.parse(fs.readFileSync(squadsJsonPath, 'utf8'));

const additionalSquads = [
  // --- 1. UD Almeria 2023-24 (28-Match Winless Streak) ---
  {
    id: "almeria-2023-24",
    clubName: "UD Almería",
    year: "2023-24",
    fullName: "UD Almería 2023-24 (28 Games Winless)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#E20613",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "alm24-suarez",
        name: "Luis Suárez",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Colombia",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 82,
        shooting: 77,
        passing: 66,
        dribbling: 75,
        defending: 35,
        physical: 79,
        composure: 75
      },
      {
        id: "alm24-robertone",
        name: "Lucas Robertone",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Argentina",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 77,
        pace: 71,
        shooting: 72,
        passing: 78,
        dribbling: 76,
        defending: 74,
        physical: 75,
        composure: 76
      },
      {
        id: "alm24-ramazani",
        name: "Largie Ramazani",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Belgium",
        league: "La Liga",
        position: "FWD",
        specificPosition: "LW",
        overall: 75,
        pace: 89,
        shooting: 73,
        passing: 69,
        dribbling: 81,
        defending: 32,
        physical: 62,
        composure: 71
      },
      {
        id: "alm24-lopy",
        name: "Dion Lopy",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Senegal",
        league: "La Liga",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 68,
        shooting: 60,
        passing: 72,
        dribbling: 73,
        defending: 75,
        physical: 80,
        composure: 72
      },
      {
        id: "alm24-melero",
        name: "Gonzalo Melero",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CAM",
        overall: 75,
        pace: 66,
        shooting: 75,
        passing: 76,
        dribbling: 74,
        defending: 64,
        physical: 70,
        composure: 76
      },
      {
        id: "alm24-akieme",
        name: "Sergio Akieme",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 76,
        pace: 86,
        shooting: 58,
        passing: 71,
        dribbling: 74,
        defending: 73,
        physical: 76,
        composure: 72
      },
      {
        id: "alm24-edgar",
        name: "Edgar González",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 74,
        pace: 56,
        shooting: 45,
        passing: 67,
        dribbling: 62,
        defending: 76,
        physical: 81,
        composure: 72
      },
      {
        id: "alm24-chumi",
        name: "Chumi",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 65,
        shooting: 32,
        passing: 60,
        dribbling: 59,
        defending: 75,
        physical: 77,
        composure: 70
      },
      {
        id: "alm24-pubill",
        name: "Marc Pubill",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 79,
        shooting: 55,
        passing: 68,
        dribbling: 71,
        defending: 74,
        physical: 78,
        composure: 72
      },
      {
        id: "alm24-embarba",
        name: "Adri Embarba",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Spain",
        league: "La Liga",
        position: "FWD",
        specificPosition: "RW",
        overall: 74,
        pace: 77,
        shooting: 74,
        passing: 75,
        dribbling: 75,
        defending: 50,
        physical: 67,
        composure: 74
      },
      {
        id: "alm24-maximiano",
        name: "Luís Maximiano",
        clubYear: "UD Almería 2023-24",
        clubName: "UD Almería",
        year: "2023-24",
        country: "Portugal",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 77,
        pace: 55,
        shooting: 25,
        passing: 68,
        dribbling: 45,
        defending: 79,
        physical: 75,
        composure: 75
      }
    ]
  },

  // --- 2. Huddersfield Town 2018-19 (16 Pts Relegation) ---
  {
    id: "huddersfield-2018-19",
    clubName: "Huddersfield Town",
    year: "2018-19",
    fullName: "Huddersfield Town 2018-19 (16 Pts)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#0E63AD",
    accentColor: "#FFFFFF",
    primaryTactic: "Gegenpress",
    players: [
      {
        id: "hud19-mounie",
        name: "Steve Mounié",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Benin",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 74,
        pace: 72,
        shooting: 74,
        passing: 58,
        dribbling: 68,
        defending: 36,
        physical: 84,
        composure: 72
      },
      {
        id: "hud19-mooy",
        name: "Aaron Mooy",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Australia",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 77,
        pace: 64,
        shooting: 73,
        passing: 81,
        dribbling: 76,
        defending: 72,
        physical: 76,
        composure: 79,
        auraTrait: {
          id: "mooy-set-piece",
          name: "Socceroo Maestro",
          description: "+25% set piece assist likelihood; reliable dead-ball delivery.",
          shortDesc: "+25% set-piece assist",
          rarity: "Rare"
        }
      },
      {
        id: "hud19-billing",
        name: "Philip Billing",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Denmark",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 75,
        pace: 68,
        shooting: 72,
        passing: 74,
        dribbling: 73,
        defending: 75,
        physical: 84,
        composure: 74
      },
      {
        id: "hud19-hogg",
        name: "Jonathan Hogg",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "England",
        league: "Premier League",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 65,
        shooting: 54,
        passing: 70,
        dribbling: 66,
        defending: 78,
        physical: 81,
        composure: 75
      },
      {
        id: "hud19-pritchard",
        name: "Alex Pritchard",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "England",
        league: "Premier League",
        position: "MID",
        specificPosition: "CAM",
        overall: 74,
        pace: 75,
        shooting: 71,
        passing: 76,
        dribbling: 78,
        defending: 42,
        physical: 62,
        composure: 74
      },
      {
        id: "hud19-schindler",
        name: "Christopher Schindler",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Germany",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 77,
        pace: 60,
        shooting: 35,
        passing: 65,
        dribbling: 62,
        defending: 80,
        physical: 80,
        composure: 77
      },
      {
        id: "hud19-zanka",
        name: "Mathias Zanka Jørgensen",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Denmark",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 75,
        pace: 62,
        shooting: 38,
        passing: 64,
        dribbling: 60,
        defending: 77,
        physical: 82,
        composure: 73
      },
      {
        id: "hud19-kongolo",
        name: "Terence Kongolo",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Netherlands",
        league: "Premier League",
        position: "DEF",
        specificPosition: "LB",
        overall: 76,
        pace: 75,
        shooting: 45,
        passing: 68,
        dribbling: 71,
        defending: 78,
        physical: 78,
        composure: 74
      },
      {
        id: "hud19-hadergjonaj",
        name: "Florent Hadergjonaj",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Kosovo",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 78,
        shooting: 52,
        passing: 69,
        dribbling: 72,
        defending: 73,
        physical: 73,
        composure: 71
      },
      {
        id: "hud19-depoitre",
        name: "Laurent Depoitre",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Belgium",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 73,
        pace: 63,
        shooting: 73,
        passing: 58,
        dribbling: 65,
        defending: 38,
        physical: 86,
        composure: 72
      },
      {
        id: "hud19-lossl",
        name: "Jonas Lössl",
        clubYear: "Huddersfield Town 2018-19",
        clubName: "Huddersfield Town",
        year: "2018-19",
        country: "Denmark",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 76,
        pace: 52,
        shooting: 22,
        passing: 66,
        dribbling: 45,
        defending: 78,
        physical: 76,
        composure: 75
      }
    ]
  },

  // --- 3. Pescara 2016-17 (Serie A 18 Pts Calamity) ---
  {
    id: "pescara-2016-17",
    clubName: "Pescara",
    year: "2016-17",
    fullName: "Pescara 2016-17 (Serie A 18 Pts)",
    type: "club",
    league: "Serie A",
    countryCode: "ITA",
    badgeColor: "#007FFF",
    accentColor: "#FFFFFF",
    primaryTactic: "Tiki-Taka",
    players: [
      {
        id: "pes17-caprari",
        name: "Gianluca Caprari",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "FWD",
        specificPosition: "LW",
        overall: 76,
        pace: 84,
        shooting: 75,
        passing: 73,
        dribbling: 81,
        defending: 36,
        physical: 64,
        composure: 75
      },
      {
        id: "pes17-benali",
        name: "Ahmad Benali",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Libya",
        league: "Serie A",
        position: "MID",
        specificPosition: "CM",
        overall: 74,
        pace: 75,
        shooting: 71,
        passing: 74,
        dribbling: 77,
        defending: 64,
        physical: 68,
        composure: 73
      },
      {
        id: "pes17-memushaj",
        name: "Ledian Memushaj",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Albania",
        league: "Serie A",
        position: "MID",
        specificPosition: "CM",
        overall: 75,
        pace: 70,
        shooting: 72,
        passing: 77,
        dribbling: 74,
        defending: 71,
        physical: 74,
        composure: 76
      },
      {
        id: "pes17-brugman",
        name: "Gastón Brugman",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Uruguay",
        league: "Serie A",
        position: "MID",
        specificPosition: "CDM",
        overall: 74,
        pace: 68,
        shooting: 68,
        passing: 78,
        dribbling: 76,
        defending: 72,
        physical: 71,
        composure: 75
      },
      {
        id: "pes17-verre",
        name: "Valerio Verre",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "MID",
        specificPosition: "CAM",
        overall: 74,
        pace: 72,
        shooting: 72,
        passing: 75,
        dribbling: 77,
        defending: 60,
        physical: 70,
        composure: 74
      },
      {
        id: "pes17-campagnaro",
        name: "Hugo Campagnaro",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Argentina",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 58,
        shooting: 40,
        passing: 66,
        dribbling: 62,
        defending: 81,
        physical: 80,
        composure: 78
      },
      {
        id: "pes17-biraghi",
        name: "Cristiano Biraghi",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "LB",
        overall: 75,
        pace: 76,
        shooting: 64,
        passing: 77,
        dribbling: 73,
        defending: 73,
        physical: 75,
        composure: 74
      },
      {
        id: "pes17-zampano",
        name: "Francesco Zampano",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 82,
        shooting: 50,
        passing: 68,
        dribbling: 73,
        defending: 72,
        physical: 72,
        composure: 71
      },
      {
        id: "pes17-fornasier",
        name: "Michele Fornasier",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 72,
        pace: 60,
        shooting: 30,
        passing: 62,
        dribbling: 58,
        defending: 74,
        physical: 76,
        composure: 70
      },
      {
        id: "pes17-cerri",
        name: "Alberto Cerri",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Italy",
        league: "Serie A",
        position: "FWD",
        specificPosition: "ST",
        overall: 72,
        pace: 62,
        shooting: 73,
        passing: 58,
        dribbling: 66,
        defending: 32,
        physical: 85,
        composure: 71
      },
      {
        id: "pes17-bizzarri",
        name: "Albano Bizzarri",
        clubYear: "Pescara 2016-17",
        clubName: "Pescara",
        year: "2016-17",
        country: "Argentina",
        league: "Serie A",
        position: "GK",
        specificPosition: "GK",
        overall: 75,
        pace: 50,
        shooting: 20,
        passing: 64,
        dribbling: 44,
        defending: 77,
        physical: 74,
        composure: 75
      }
    ]
  },

  // --- 4. Greuther Furth 2021-22 (Bundesliga 18 Pts) ---
  {
    id: "greuther-furth-2021-22",
    clubName: "Greuther Fürth",
    year: "2021-22",
    fullName: "Greuther Fürth 2021-22 (18 Pts)",
    type: "club",
    league: "Bundesliga",
    countryCode: "GER",
    badgeColor: "#009933",
    accentColor: "#FFFFFF",
    primaryTactic: "Gegenpress",
    players: [
      {
        id: "fur22-hrgota",
        name: "Branimir Hrgota",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Sweden",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 75,
        shooting: 77,
        passing: 73,
        dribbling: 77,
        defending: 40,
        physical: 72,
        composure: 78
      },
      {
        id: "fur22-tillman",
        name: "Timothy Tillman",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "USA",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CM",
        overall: 74,
        pace: 76,
        shooting: 68,
        passing: 75,
        dribbling: 77,
        defending: 67,
        physical: 71,
        composure: 74
      },
      {
        id: "fur22-seguin",
        name: "Paul Seguin",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Germany",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CDM",
        overall: 75,
        pace: 71,
        shooting: 70,
        passing: 76,
        dribbling: 74,
        defending: 75,
        physical: 76,
        composure: 75
      },
      {
        id: "fur22-green",
        name: "Julian Green",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "USA",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CAM",
        overall: 73,
        pace: 74,
        shooting: 73,
        passing: 72,
        dribbling: 76,
        defending: 50,
        physical: 66,
        composure: 73
      },
      {
        id: "fur22-leweling",
        name: "Jamie Leweling",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Germany",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "RW",
        overall: 75,
        pace: 88,
        shooting: 72,
        passing: 68,
        dribbling: 78,
        defending: 42,
        physical: 75,
        composure: 72
      },
      {
        id: "fur22-viergever",
        name: "Nick Viergever",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Netherlands",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 74,
        pace: 60,
        shooting: 48,
        passing: 69,
        dribbling: 64,
        defending: 76,
        physical: 76,
        composure: 76
      },
      {
        id: "fur22-willems",
        name: "Jetro Willems",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Netherlands",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 77,
        shooting: 68,
        passing: 75,
        dribbling: 76,
        defending: 71,
        physical: 76,
        composure: 74
      },
      {
        id: "fur22-bauer",
        name: "Maximilian Bauer",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 72,
        pace: 65,
        shooting: 30,
        passing: 60,
        dribbling: 56,
        defending: 74,
        physical: 78,
        composure: 70
      },
      {
        id: "fur22-meyerhofer",
        name: "Marco Meyerhöfer",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "RB",
        overall: 73,
        pace: 79,
        shooting: 52,
        passing: 67,
        dribbling: 70,
        defending: 73,
        physical: 72,
        composure: 71
      },
      {
        id: "fur22-nielsen",
        name: "Havard Nielsen",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Norway",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 73,
        pace: 73,
        shooting: 73,
        passing: 68,
        dribbling: 72,
        defending: 45,
        physical: 76,
        composure: 73
      },
      {
        id: "fur22-burchert",
        name: "Sascha Burchert",
        clubYear: "Greuther Fürth 2021-22",
        clubName: "Greuther Fürth",
        year: "2021-22",
        country: "Germany",
        league: "Bundesliga",
        position: "GK",
        specificPosition: "GK",
        overall: 74,
        pace: 50,
        shooting: 20,
        passing: 66,
        dribbling: 45,
        defending: 76,
        physical: 73,
        composure: 74
      }
    ]
  },

  // --- 5. Aston Villa 2015-16 (17 Pts Premier League Demise) ---
  {
    id: "aston-villa-2015-16",
    clubName: "Aston Villa",
    year: "2015-16",
    fullName: "Aston Villa 2015-16 (17 Pts Disaster)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#95BFE5",
    accentColor: "#670E36",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "av16-ayew",
        name: "Jordan Ayew",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Ghana",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 77,
        pace: 82,
        shooting: 76,
        passing: 72,
        dribbling: 79,
        defending: 44,
        physical: 77,
        composure: 75
      },
      {
        id: "av16-gueye",
        name: "Idrissa Gueye",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Senegal",
        league: "Premier League",
        position: "MID",
        specificPosition: "CDM",
        overall: 78,
        pace: 75,
        shooting: 62,
        passing: 74,
        dribbling: 75,
        defending: 82,
        physical: 80,
        composure: 78
      },
      {
        id: "av16-veretout",
        name: "Jordan Veretout",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "France",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 76,
        pace: 72,
        shooting: 72,
        passing: 78,
        dribbling: 76,
        defending: 71,
        physical: 73,
        composure: 76
      },
      {
        id: "av16-gil",
        name: "Carles Gil",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Spain",
        league: "Premier League",
        position: "MID",
        specificPosition: "CAM",
        overall: 75,
        pace: 74,
        shooting: 71,
        passing: 77,
        dribbling: 81,
        defending: 38,
        physical: 58,
        composure: 75
      },
      {
        id: "av16-gestede",
        name: "Rudy Gestede",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Benin",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 74,
        pace: 64,
        shooting: 74,
        passing: 55,
        dribbling: 64,
        defending: 35,
        physical: 88,
        composure: 73
      },
      {
        id: "av16-richards",
        name: "Micah Richards",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 78,
        shooting: 45,
        passing: 62,
        dribbling: 66,
        defending: 77,
        physical: 86,
        composure: 72
      },
      {
        id: "av16-lescott",
        name: "Joleon Lescott",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 76,
        pace: 56,
        shooting: 40,
        passing: 65,
        dribbling: 60,
        defending: 79,
        physical: 82,
        composure: 75
      },
      {
        id: "av16-clark",
        name: "Ciaran Clark",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Ireland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 75,
        pace: 64,
        shooting: 42,
        passing: 64,
        dribbling: 58,
        defending: 77,
        physical: 80,
        composure: 73
      },
      {
        id: "av16-hutton",
        name: "Alan Hutton",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Scotland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 80,
        shooting: 54,
        passing: 68,
        dribbling: 70,
        defending: 74,
        physical: 80,
        composure: 72
      },
      {
        id: "av16-bacuna",
        name: "Leandro Bacuna",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "Curacao",
        league: "Premier League",
        position: "MID",
        specificPosition: "RM",
        overall: 74,
        pace: 81,
        shooting: 70,
        passing: 72,
        dribbling: 74,
        defending: 68,
        physical: 76,
        composure: 72
      },
      {
        id: "av16-guzan",
        name: "Brad Guzan",
        clubYear: "Aston Villa 2015-16",
        clubName: "Aston Villa",
        year: "2015-16",
        country: "USA",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 76,
        pace: 52,
        shooting: 22,
        passing: 65,
        dribbling: 45,
        defending: 77,
        physical: 77,
        composure: 75
      }
    ]
  },

  // --- 6. Levante UD 2007-08 (Financial Meltdown) ---
  {
    id: "levante-2007-08",
    clubName: "Levante UD",
    year: "2007-08",
    fullName: "Levante UD 2007-08 (26 Pts Meltdown)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#003399",
    accentColor: "#CC0000",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "lev08-riga",
        name: "Mustapha Riga",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Netherlands",
        league: "La Liga",
        position: "FWD",
        specificPosition: "RW",
        overall: 76,
        pace: 84,
        shooting: 75,
        passing: 71,
        dribbling: 78,
        defending: 38,
        physical: 72,
        composure: 75
      },
      {
        id: "lev08-geijo",
        name: "Alexandre Geijo",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Switzerland",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 72,
        shooting: 76,
        passing: 62,
        dribbling: 71,
        defending: 35,
        physical: 81,
        composure: 74
      },
      {
        id: "lev08-courtois",
        name: "Laurent Courtois",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "France",
        league: "La Liga",
        position: "MID",
        specificPosition: "LM",
        overall: 74,
        pace: 78,
        shooting: 71,
        passing: 74,
        dribbling: 76,
        defending: 52,
        physical: 68,
        composure: 73
      },
      {
        id: "lev08-berson",
        name: "Mathieu Berson",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "France",
        league: "La Liga",
        position: "MID",
        specificPosition: "CDM",
        overall: 75,
        pace: 68,
        shooting: 62,
        passing: 75,
        dribbling: 71,
        defending: 77,
        physical: 78,
        composure: 76
      },
      {
        id: "lev08-miguel",
        name: "Miguel Ángel",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 73,
        pace: 66,
        shooting: 66,
        passing: 74,
        dribbling: 72,
        defending: 73,
        physical: 74,
        composure: 73
      },
      {
        id: "lev08-juanma",
        name: "Juanma",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "RM",
        overall: 73,
        pace: 78,
        shooting: 68,
        passing: 71,
        dribbling: 75,
        defending: 48,
        physical: 68,
        composure: 72
      },
      {
        id: "lev08-descarga",
        name: "Iñaki Descarga",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 74,
        shooting: 45,
        passing: 66,
        dribbling: 67,
        defending: 75,
        physical: 76,
        composure: 74
      },
      {
        id: "lev08-rubiales",
        name: "Luis Rubiales",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 72,
        pace: 70,
        shooting: 40,
        passing: 64,
        dribbling: 63,
        defending: 73,
        physical: 75,
        composure: 68
      },
      {
        id: "lev08-serrano",
        name: "José Serrano",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 72,
        pace: 61,
        shooting: 32,
        passing: 60,
        dribbling: 56,
        defending: 74,
        physical: 77,
        composure: 71
      },
      {
        id: "lev08-castedo",
        name: "David Castedo",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Spain",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 71,
        shooting: 48,
        passing: 69,
        dribbling: 68,
        defending: 76,
        physical: 74,
        composure: 74
      },
      {
        id: "lev08-storari",
        name: "Marco Storari",
        clubYear: "Levante UD 2007-08",
        clubName: "Levante UD",
        year: "2007-08",
        country: "Italy",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 77,
        pace: 54,
        shooting: 25,
        passing: 66,
        dribbling: 48,
        defending: 79,
        physical: 75,
        composure: 77
      }
    ]
  },

  // --- 7. Anzhi Makhachkala 2013-14 (The Fire Sale) ---
  {
    id: "anzhi-2013-14",
    clubName: "Anzhi Makhachkala",
    year: "2013-14",
    fullName: "Anzhi Makhachkala 2013-14 (Fire Sale)",
    type: "club",
    league: "Other",
    countryCode: "RUS",
    badgeColor: "#F4C430",
    accentColor: "#006633",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "anz14-smolov",
        name: "Fedor Smolov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 81,
        shooting: 76,
        passing: 68,
        dribbling: 76,
        defending: 36,
        physical: 76,
        composure: 74
      },
      {
        id: "anz14-ahmedov",
        name: "Odil Ahmedov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Uzbekistan",
        league: "Other",
        position: "MID",
        specificPosition: "CM",
        overall: 77,
        pace: 73,
        shooting: 72,
        passing: 79,
        dribbling: 76,
        defending: 76,
        physical: 78,
        composure: 77
      },
      {
        id: "anz14-jucilei",
        name: "Jucilei",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Brazil",
        league: "Other",
        position: "MID",
        specificPosition: "CDM",
        overall: 77,
        pace: 68,
        shooting: 66,
        passing: 76,
        dribbling: 74,
        defending: 79,
        physical: 84,
        composure: 76
      },
      {
        id: "anz14-bystrov",
        name: "Vladimir Bystrov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "MID",
        specificPosition: "RM",
        overall: 76,
        pace: 86,
        shooting: 72,
        passing: 73,
        dribbling: 79,
        defending: 48,
        physical: 68,
        composure: 74
      },
      {
        id: "anz14-bilyaletdinov",
        name: "Diniyar Bilyaletdinov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "MID",
        specificPosition: "CAM",
        overall: 75,
        pace: 72,
        shooting: 76,
        passing: 77,
        dribbling: 77,
        defending: 52,
        physical: 70,
        composure: 75
      },
      {
        id: "anz14-samba",
        name: "Christopher Samba",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Congo",
        league: "Other",
        position: "DEF",
        specificPosition: "CB",
        overall: 78,
        pace: 62,
        shooting: 45,
        passing: 60,
        dribbling: 56,
        defending: 80,
        physical: 90,
        composure: 75
      },
      {
        id: "anz14-eschenko",
        name: "Andrei Eschenko",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "DEF",
        specificPosition: "RB",
        overall: 74,
        pace: 79,
        shooting: 52,
        passing: 68,
        dribbling: 71,
        defending: 74,
        physical: 75,
        composure: 72
      },
      {
        id: "anz14-angbwa",
        name: "Benoit Angbwa",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Cameroon",
        league: "Other",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 78,
        shooting: 50,
        passing: 67,
        dribbling: 69,
        defending: 75,
        physical: 77,
        composure: 73
      },
      {
        id: "anz14-gadzhibekov",
        name: "Ali Gadzhibekov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 65,
        shooting: 35,
        passing: 60,
        dribbling: 58,
        defending: 75,
        physical: 78,
        composure: 71
      },
      {
        id: "anz14-bukharov",
        name: "Aleksandr Bukharov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "FWD",
        specificPosition: "ST",
        overall: 75,
        pace: 72,
        shooting: 76,
        passing: 62,
        dribbling: 70,
        defending: 38,
        physical: 84,
        composure: 74
      },
      {
        id: "anz14-gabulov",
        name: "Vladimir Gabulov",
        clubYear: "Anzhi Makhachkala 2013-14",
        clubName: "Anzhi Makhachkala",
        year: "2013-14",
        country: "Russia",
        league: "Other",
        position: "GK",
        specificPosition: "GK",
        overall: 77,
        pace: 52,
        shooting: 24,
        passing: 68,
        dribbling: 45,
        defending: 79,
        physical: 76,
        composure: 76
      }
    ]
  },

  // --- 8. Anorthosis Famagusta 2008-09 (Cinderella UCL Miracles) ---
  {
    id: "anorthosis-2008-09",
    clubName: "Anorthosis Famagusta",
    year: "2008-09",
    fullName: "Anorthosis Famagusta 2008-09 (UCL Underdogs)",
    type: "club",
    league: "Other",
    countryCode: "CYP",
    badgeColor: "#0047AB",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "ano09-sosin",
        name: "Lukasz Sosin",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Poland",
        league: "Other",
        position: "FWD",
        specificPosition: "ST",
        overall: 76,
        pace: 73,
        shooting: 78,
        passing: 62,
        dribbling: 70,
        defending: 36,
        physical: 82,
        composure: 76
      },
      {
        id: "ano09-savio",
        name: "Sávio",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Brazil",
        league: "Other",
        position: "FWD",
        specificPosition: "LW",
        overall: 77,
        pace: 75,
        shooting: 75,
        passing: 80,
        dribbling: 82,
        defending: 40,
        physical: 66,
        composure: 81
      },
      {
        id: "ano09-hawar",
        name: "Hawar Mulla Mohammed",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Iraq",
        league: "Other",
        position: "MID",
        specificPosition: "LM",
        overall: 75,
        pace: 82,
        shooting: 74,
        passing: 74,
        dribbling: 78,
        defending: 48,
        physical: 70,
        composure: 75
      },
      {
        id: "ano09-skopelitis",
        name: "Giannis Skopelitis",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Greece",
        league: "Other",
        position: "MID",
        specificPosition: "CDM",
        overall: 75,
        pace: 68,
        shooting: 62,
        passing: 75,
        dribbling: 71,
        defending: 78,
        physical: 79,
        composure: 76
      },
      {
        id: "ano09-laban",
        name: "Vincent Laban",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "France",
        league: "Other",
        position: "MID",
        specificPosition: "CM",
        overall: 74,
        pace: 72,
        shooting: 70,
        passing: 76,
        dribbling: 75,
        defending: 71,
        physical: 72,
        composure: 75
      },
      {
        id: "ano09-dellas",
        name: "Traianos Dellas",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Greece",
        league: "Other",
        position: "DEF",
        specificPosition: "CB",
        overall: 78,
        pace: 54,
        shooting: 45,
        passing: 68,
        dribbling: 60,
        defending: 82,
        physical: 86,
        composure: 82,
        auraTrait: {
          id: "dellas-wall-cyp",
          name: "Colossus of Famagusta",
          description: "+30% headed clearances and aerial dominance in European ties.",
          shortDesc: "+30% aerial defense",
          rarity: "Rare"
        }
      },
      {
        id: "ano09-katsavakis",
        name: "Nikos Katsavakis",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Greece",
        league: "Other",
        position: "DEF",
        specificPosition: "CB",
        overall: 73,
        pace: 64,
        shooting: 32,
        passing: 62,
        dribbling: 58,
        defending: 75,
        physical: 79,
        composure: 72
      },
      {
        id: "ano09-leiwakabessy",
        name: "Jeffrey Leiwakabessy",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Netherlands",
        league: "Other",
        position: "DEF",
        specificPosition: "LB",
        overall: 74,
        pace: 78,
        shooting: 46,
        passing: 68,
        dribbling: 71,
        defending: 74,
        physical: 73,
        composure: 73
      },
      {
        id: "ano09-georgiou",
        name: "Georgios Georgiou",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Cyprus",
        league: "Other",
        position: "DEF",
        specificPosition: "RB",
        overall: 72,
        pace: 74,
        shooting: 42,
        passing: 65,
        dribbling: 66,
        defending: 73,
        physical: 73,
        composure: 70
      },
      {
        id: "ano09-tsitaishvili",
        name: "Klimenti Tsitaishvili",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Georgia",
        league: "Other",
        position: "FWD",
        specificPosition: "ST",
        overall: 72,
        pace: 75,
        shooting: 72,
        passing: 63,
        dribbling: 72,
        defending: 36,
        physical: 75,
        composure: 72
      },
      {
        id: "ano09-beqaj",
        name: "Arian Beqaj",
        clubYear: "Anorthosis Famagusta 2008-09",
        clubName: "Anorthosis Famagusta",
        year: "2008-09",
        country: "Albania",
        league: "Other",
        position: "GK",
        specificPosition: "GK",
        overall: 75,
        pace: 52,
        shooting: 20,
        passing: 65,
        dribbling: 45,
        defending: 77,
        physical: 75,
        composure: 76
      }
    ]
  },

  // --- 9. Greece 2004 (100-1 Euro Upset Champions) ---
  {
    id: "greece-2004",
    clubName: "Greece",
    year: "2004",
    fullName: "Greece 2004 (100-1 Euro Champions)",
    type: "country",
    league: "International",
    countryCode: "GRE",
    badgeColor: "#0D5EAF",
    accentColor: "#FFFFFF",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "gre04-charisteas",
        name: "Angelos Charisteas",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 84,
        pace: 78,
        shooting: 84,
        passing: 69,
        dribbling: 76,
        defending: 42,
        physical: 85,
        composure: 86,
        auraTrait: {
          id: "charisteas-header",
          name: "Lethal Euro Header",
          description: "+40% conversion on set-piece corner headers in knockout matches.",
          shortDesc: "+40% corner header xG",
          rarity: "Epic"
        }
      },
      {
        id: "gre04-zagorakis",
        name: "Theodoros Zagorakis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 85,
        pace: 74,
        shooting: 76,
        passing: 84,
        dribbling: 81,
        defending: 85,
        physical: 84,
        composure: 88,
        auraTrait: {
          id: "zagorakis-mvp",
          name: "Euro 2004 Player of Tournament",
          description: "+15% entire team defensive organization when leading.",
          shortDesc: "+15% team defensive org",
          rarity: "Legendary"
        }
      },
      {
        id: "gre04-karagounis",
        name: "Giorgos Karagounis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "MID",
        specificPosition: "CAM",
        overall: 84,
        pace: 77,
        shooting: 82,
        passing: 85,
        dribbling: 84,
        defending: 72,
        physical: 79,
        composure: 86
      },
      {
        id: "gre04-katsouranis",
        name: "Kostas Katsouranis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 83,
        pace: 73,
        shooting: 75,
        passing: 81,
        dribbling: 77,
        defending: 83,
        physical: 83,
        composure: 84
      },
      {
        id: "gre04-basinas",
        name: "Angelos Basinas",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 82,
        pace: 70,
        shooting: 77,
        passing: 83,
        dribbling: 76,
        defending: 81,
        physical: 80,
        composure: 83
      },
      {
        id: "gre04-vryzas",
        name: "Zisis Vryzas",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 80,
        pace: 75,
        shooting: 80,
        passing: 70,
        dribbling: 76,
        defending: 40,
        physical: 83,
        composure: 80
      },
      {
        id: "gre04-dellas",
        name: "Traianos Dellas",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 86,
        pace: 60,
        shooting: 55,
        passing: 72,
        dribbling: 66,
        defending: 89,
        physical: 90,
        composure: 88,
        auraTrait: {
          id: "dellas-silver-goal",
          name: "The Colossus of Rhodes",
          description: "+30% box clearances; scored iconic Euro 2004 silver goal.",
          shortDesc: "+30% box clearances",
          rarity: "Epic"
        }
      },
      {
        id: "gre04-kapsis",
        name: "Michalis Kapsis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 83,
        pace: 70,
        shooting: 35,
        passing: 68,
        dribbling: 64,
        defending: 85,
        physical: 84,
        composure: 82
      },
      {
        id: "gre04-seitaridis",
        name: "Giourkas Seitaridis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 84,
        pace: 86,
        shooting: 60,
        passing: 77,
        dribbling: 79,
        defending: 83,
        physical: 82,
        composure: 82
      },
      {
        id: "gre04-fyssas",
        name: "Takis Fyssas",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 82,
        pace: 79,
        shooting: 58,
        passing: 76,
        dribbling: 75,
        defending: 82,
        physical: 80,
        composure: 81
      },
      {
        id: "gre04-nikopolidis",
        name: "Antonis Nikopolidis",
        clubYear: "Greece 2004",
        clubName: "Greece",
        year: "2004",
        country: "Greece",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 85,
        pace: 56,
        shooting: 28,
        passing: 74,
        dribbling: 50,
        defending: 86,
        physical: 83,
        composure: 89
      }
    ]
  },

  // --- 10. Costa Rica 2014 (Death Group Miracle) ---
  {
    id: "costa-rica-2014",
    clubName: "Costa Rica",
    year: "2014",
    fullName: "Costa Rica 2014 (Death Group Toppers)",
    type: "country",
    league: "International",
    countryCode: "CRC",
    badgeColor: "#002B7F",
    accentColor: "#CE1126",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "crc14-ruiz",
        name: "Bryan Ruiz",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "MID",
        specificPosition: "CAM",
        overall: 84,
        pace: 74,
        shooting: 82,
        passing: 86,
        dribbling: 85,
        defending: 52,
        physical: 72,
        composure: 87,
        auraTrait: {
          id: "ruiz-comadreja",
          name: "El Capitán Clutch",
          description: "+25% conversion on knockout match winning attempts.",
          shortDesc: "+25% clutch winner xG",
          rarity: "Epic"
        }
      },
      {
        id: "crc14-campbell",
        name: "Joel Campbell",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 83,
        pace: 88,
        shooting: 81,
        passing: 76,
        dribbling: 85,
        defending: 40,
        physical: 76,
        composure: 82
      },
      {
        id: "crc14-borges",
        name: "Celso Borges",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 82,
        pace: 71,
        shooting: 77,
        passing: 82,
        dribbling: 77,
        defending: 79,
        physical: 81,
        composure: 84
      },
      {
        id: "crc14-tejeda",
        name: "Yeltsin Tejeda",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 80,
        pace: 76,
        shooting: 64,
        passing: 76,
        dribbling: 74,
        defending: 81,
        physical: 80,
        composure: 79
      },
      {
        id: "crc14-bolanos",
        name: "Christian Bolaños",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "MID",
        specificPosition: "RM",
        overall: 80,
        pace: 78,
        shooting: 74,
        passing: 80,
        dribbling: 80,
        defending: 50,
        physical: 68,
        composure: 80
      },
      {
        id: "crc14-gonzalez",
        name: "Giancarlo González",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 82,
        pace: 68,
        shooting: 40,
        passing: 68,
        dribbling: 64,
        defending: 85,
        physical: 85,
        composure: 82
      },
      {
        id: "crc14-duarte",
        name: "Óscar Duarte",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 70,
        shooting: 48,
        passing: 69,
        dribbling: 65,
        defending: 83,
        physical: 82,
        composure: 80
      },
      {
        id: "crc14-umana",
        name: "Michael Umaña",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 80,
        pace: 64,
        shooting: 38,
        passing: 66,
        dribbling: 62,
        defending: 82,
        physical: 81,
        composure: 81
      },
      {
        id: "crc14-gamboa",
        name: "Cristian Gamboa",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 81,
        pace: 90,
        shooting: 55,
        passing: 73,
        dribbling: 77,
        defending: 78,
        physical: 76,
        composure: 78
      },
      {
        id: "crc14-diaz",
        name: "Júnior Díaz",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 80,
        pace: 82,
        shooting: 56,
        passing: 75,
        dribbling: 74,
        defending: 79,
        physical: 78,
        composure: 79
      },
      {
        id: "crc14-navas",
        name: "Keylor Navas",
        clubYear: "Costa Rica 2014",
        clubName: "Costa Rica",
        year: "2014",
        country: "Costa Rica",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 89,
        pace: 62,
        shooting: 30,
        passing: 76,
        dribbling: 54,
        defending: 91,
        physical: 84,
        composure: 92,
        auraTrait: {
          id: "navas-san-keylor",
          name: "San Keylor Wall",
          description: "+35% save reflex on shots within 12 yards; conceded only 2 open play goals all tournament.",
          shortDesc: "+35% close-range saves",
          rarity: "Legendary"
        }
      }
    ]
  },

  // --- 11. Senegal 2002 (Lions of Teranga Quarter-Finalists) ---
  {
    id: "senegal-2002",
    clubName: "Senegal",
    year: "2002",
    fullName: "Senegal 2002 (Lions of Teranga)",
    type: "country",
    league: "International",
    countryCode: "SEN",
    badgeColor: "#00853F",
    accentColor: "#FDEF42",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "sen02-diouf",
        name: "El Hadji Diouf",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 86,
        pace: 89,
        shooting: 83,
        passing: 79,
        dribbling: 88,
        defending: 45,
        physical: 82,
        composure: 85,
        auraTrait: {
          id: "diouf-terror",
          name: "Terror of Seoul",
          description: "+30% dribble success vs World Champions France; drawing 2x yellow cards.",
          shortDesc: "+30% take-on win rate",
          rarity: "Epic"
        }
      },
      {
        id: "sen02-diop",
        name: "Papa Bouba Diop",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 84,
        pace: 72,
        shooting: 78,
        passing: 78,
        dribbling: 76,
        defending: 85,
        physical: 93,
        composure: 84,
        auraTrait: {
          id: "diop-wardrobe",
          name: "The Wardrobe",
          description: "+35% ground duel win rate and physically dominates opposition midfield.",
          shortDesc: "+35% midfield duels",
          rarity: "Legendary"
        }
      },
      {
        id: "sen02-fadiga",
        name: "Khalilou Fadiga",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "MID",
        specificPosition: "CAM",
        overall: 84,
        pace: 82,
        shooting: 80,
        passing: 86,
        dribbling: 87,
        defending: 48,
        physical: 74,
        composure: 83
      },
      {
        id: "sen02-camara",
        name: "Henri Camara",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 83,
        pace: 91,
        shooting: 81,
        passing: 71,
        dribbling: 82,
        defending: 38,
        physical: 75,
        composure: 82
      },
      {
        id: "sen02-diao",
        name: "Salif Diao",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 82,
        pace: 75,
        shooting: 72,
        passing: 78,
        dribbling: 76,
        defending: 82,
        physical: 85,
        composure: 81
      },
      {
        id: "sen02-cisse",
        name: "Aliou Cissé",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 82,
        pace: 72,
        shooting: 50,
        passing: 74,
        dribbling: 68,
        defending: 83,
        physical: 85,
        composure: 86
      },
      {
        id: "sen02-diatta",
        name: "Lamine Diatta",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 71,
        shooting: 40,
        passing: 68,
        dribbling: 62,
        defending: 83,
        physical: 84,
        composure: 80
      },
      {
        id: "sen02-coly",
        name: "Ferdinand Coly",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 81,
        pace: 82,
        shooting: 48,
        passing: 72,
        dribbling: 73,
        defending: 81,
        physical: 81,
        composure: 80
      },
      {
        id: "sen02-daf",
        name: "Omar Daf",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 80,
        pace: 80,
        shooting: 46,
        passing: 73,
        dribbling: 72,
        defending: 80,
        physical: 78,
        composure: 79
      },
      {
        id: "sen02-ndour",
        name: "Alassane N'Dour",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "MID",
        specificPosition: "LM",
        overall: 79,
        pace: 81,
        shooting: 68,
        passing: 74,
        dribbling: 76,
        defending: 64,
        physical: 76,
        composure: 78
      },
      {
        id: "sen02-sylva",
        name: "Tony Sylva",
        clubYear: "Senegal 2002",
        clubName: "Senegal",
        year: "2002",
        country: "Senegal",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 83,
        pace: 55,
        shooting: 25,
        passing: 70,
        dribbling: 48,
        defending: 84,
        physical: 81,
        composure: 84
      }
    ]
  },

  // --- 12. South Korea 2002 (Semi-Final Storm) ---
  {
    id: "south-korea-2002",
    clubName: "South Korea",
    year: "2002",
    fullName: "South Korea 2002 (Semi-Final Storm)",
    type: "country",
    league: "International",
    countryCode: "KOR",
    badgeColor: "#C60C30",
    accentColor: "#003478",
    primaryTactic: "Gegenpress",
    players: [
      {
        id: "kor02-park",
        name: "Park Ji-sung",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "MID",
        specificPosition: "RM",
        overall: 86,
        pace: 86,
        shooting: 79,
        passing: 82,
        dribbling: 84,
        defending: 78,
        physical: 88,
        composure: 89,
        auraTrait: {
          id: "park-three-lungs",
          name: "Three-Lungs Park",
          description: "+25% pressing efficiency in 80th-90th minutes; relentless recovery running.",
          shortDesc: "+25% late pressing",
          rarity: "Legendary"
        }
      },
      {
        id: "kor02-ahn",
        name: "Ahn Jung-hwan",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 84,
        pace: 84,
        shooting: 84,
        passing: 77,
        dribbling: 86,
        defending: 40,
        physical: 76,
        composure: 86,
        auraTrait: {
          id: "ahn-golden-goal",
          name: "Golden Goal Hero",
          description: "+35% conversion in extra time; knocked out Italy with iconic header.",
          shortDesc: "+35% extra-time xG",
          rarity: "Epic"
        }
      },
      {
        id: "kor02-hong",
        name: "Hong Myung-bo",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 87,
        pace: 75,
        shooting: 68,
        passing: 84,
        dribbling: 76,
        defending: 88,
        physical: 84,
        composure: 90,
        auraTrait: {
          id: "hong-bronze-ball",
          name: "World Cup Bronze Ball",
          description: "+20% backline intercept range; scored decisive penalty vs Spain.",
          shortDesc: "+20% backline interceptions",
          rarity: "Legendary"
        }
      },
      {
        id: "kor02-yoo",
        name: "Yoo Sang-chul",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 83,
        pace: 77,
        shooting: 80,
        passing: 81,
        dribbling: 79,
        defending: 80,
        physical: 84,
        composure: 84
      },
      {
        id: "kor02-kim",
        name: "Kim Nam-il",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 82,
        pace: 78,
        shooting: 66,
        passing: 78,
        dribbling: 75,
        defending: 84,
        physical: 86,
        composure: 82
      },
      {
        id: "kor02-lee-yp",
        name: "Lee Young-pyo",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 83,
        pace: 85,
        shooting: 64,
        passing: 78,
        dribbling: 83,
        defending: 81,
        physical: 76,
        composure: 83
      },
      {
        id: "kor02-song",
        name: "Song Chong-gug",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 82,
        pace: 84,
        shooting: 62,
        passing: 76,
        dribbling: 78,
        defending: 82,
        physical: 80,
        composure: 81
      },
      {
        id: "kor02-choi",
        name: "Choi Jin-cheul",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 68,
        shooting: 40,
        passing: 66,
        dribbling: 60,
        defending: 83,
        physical: 85,
        composure: 80
      },
      {
        id: "kor02-seol",
        name: "Seol Ki-hyeon",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "FWD",
        specificPosition: "LW",
        overall: 82,
        pace: 83,
        shooting: 79,
        passing: 77,
        dribbling: 81,
        defending: 48,
        physical: 81,
        composure: 81
      },
      {
        id: "kor02-cha",
        name: "Cha Du-ri",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "FWD",
        specificPosition: "RW",
        overall: 80,
        pace: 90,
        shooting: 74,
        passing: 70,
        dribbling: 77,
        defending: 55,
        physical: 86,
        composure: 78
      },
      {
        id: "kor02-lee-wj",
        name: "Lee Woon-jae",
        clubYear: "South Korea 2002",
        clubName: "South Korea",
        year: "2002",
        country: "South Korea",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 84,
        pace: 54,
        shooting: 24,
        passing: 72,
        dribbling: 48,
        defending: 85,
        physical: 82,
        composure: 87
      }
    ]
  },

  // --- 13. Netherlands 2010 (Total Oranje Finalists) ---
  {
    id: "netherlands-2010",
    clubName: "Netherlands",
    year: "2010",
    fullName: "Netherlands 2010 (World Cup Finalists)",
    type: "country",
    league: "International",
    countryCode: "NED",
    badgeColor: "#F36C21",
    accentColor: "#FFFFFF",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "ned10-robben",
        name: "Arjen Robben",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "FWD",
        specificPosition: "RW",
        overall: 91,
        pace: 93,
        shooting: 89,
        passing: 83,
        dribbling: 93,
        defending: 35,
        physical: 74,
        composure: 90,
        auraTrait: {
          id: "robben-le-cut",
          name: "Cut Inside Inevitability",
          description: "+30% curl shot conversion cutting inside onto left foot.",
          shortDesc: "+30% cut-inside xG",
          rarity: "Legendary"
        }
      },
      {
        id: "ned10-sneijder",
        name: "Wesley Sneijder",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "MID",
        specificPosition: "CAM",
        overall: 92,
        pace: 79,
        shooting: 90,
        passing: 93,
        dribbling: 88,
        defending: 62,
        physical: 75,
        composure: 94,
        auraTrait: {
          id: "sneijder-silver-ball",
          name: "Silver Boot & Ball",
          description: "+35% long range shooting accuracy; scored 5 goals at 2010 World Cup.",
          shortDesc: "+35% long-range xG",
          rarity: "Legendary"
        }
      },
      {
        id: "ned10-rvp",
        name: "Robin van Persie",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 88,
        pace: 82,
        shooting: 91,
        passing: 82,
        dribbling: 88,
        defending: 38,
        physical: 77,
        composure: 90
      },
      {
        id: "ned10-kuyt",
        name: "Dirk Kuyt",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "FWD",
        specificPosition: "LW",
        overall: 85,
        pace: 80,
        shooting: 82,
        passing: 80,
        dribbling: 81,
        defending: 68,
        physical: 87,
        composure: 87
      },
      {
        id: "ned10-bommel",
        name: "Mark van Bommel",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 85,
        pace: 68,
        shooting: 78,
        passing: 84,
        dribbling: 77,
        defending: 86,
        physical: 88,
        composure: 90
      },
      {
        id: "ned10-dejong",
        name: "Nigel de Jong",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 85,
        pace: 72,
        shooting: 65,
        passing: 80,
        dribbling: 76,
        defending: 88,
        physical: 89,
        composure: 86
      },
      {
        id: "ned10-gio",
        name: "Giovanni van Bronckhorst",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 85,
        pace: 79,
        shooting: 77,
        passing: 83,
        dribbling: 80,
        defending: 84,
        physical: 80,
        composure: 89,
        auraTrait: {
          id: "gio-missile",
          name: "Uruguay Rocket",
          description: "+30% long range strike accuracy from outside 30 yards.",
          shortDesc: "+30% long-range rocket",
          rarity: "Epic"
        }
      },
      {
        id: "ned10-heitinga",
        name: "John Heitinga",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 84,
        pace: 74,
        shooting: 55,
        passing: 75,
        dribbling: 70,
        defending: 85,
        physical: 84,
        composure: 83
      },
      {
        id: "ned10-mathijsen",
        name: "Joris Mathijsen",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 84,
        pace: 71,
        shooting: 45,
        passing: 74,
        dribbling: 68,
        defending: 86,
        physical: 83,
        composure: 84
      },
      {
        id: "ned10-vdwiel",
        name: "Gregory van der Wiel",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 82,
        pace: 86,
        shooting: 58,
        passing: 78,
        dribbling: 79,
        defending: 79,
        physical: 76,
        composure: 80
      },
      {
        id: "ned10-stekelenburg",
        name: "Maarten Stekelenburg",
        clubYear: "Netherlands 2010",
        clubName: "Netherlands",
        year: "2010",
        country: "Netherlands",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 86,
        pace: 58,
        shooting: 26,
        passing: 78,
        dribbling: 52,
        defending: 87,
        physical: 82,
        composure: 87
      }
    ]
  },

  // --- 14. Saudi Arabia 2022 (Lusail Miracle) ---
  {
    id: "saudi-arabia-2022",
    clubName: "Saudi Arabia",
    year: "2022",
    fullName: "Saudi Arabia 2022 (Lusail Upset vs ARG)",
    type: "country",
    league: "International",
    countryCode: "KSA",
    badgeColor: "#006C35",
    accentColor: "#FFFFFF",
    primaryTactic: "Gegenpress",
    players: [
      {
        id: "ksa22-dawsari",
        name: "Salem Al-Dawsari",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "FWD",
        specificPosition: "LW",
        overall: 84,
        pace: 86,
        shooting: 83,
        passing: 79,
        dribbling: 87,
        defending: 46,
        physical: 72,
        composure: 86,
        auraTrait: {
          id: "dawsari-lusail-rocket",
          name: "The Lusail Screamer",
          description: "+35% curling shot accuracy when cutting inside against higher-rated giants.",
          shortDesc: "+35% giant-killing curl",
          rarity: "Epic"
        }
      },
      {
        id: "ksa22-shehri",
        name: "Saleh Al-Shehri",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 80,
        pace: 79,
        shooting: 81,
        passing: 70,
        dribbling: 77,
        defending: 38,
        physical: 78,
        composure: 81
      },
      {
        id: "ksa22-kanno",
        name: "Mohamed Kanno",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 81,
        pace: 75,
        shooting: 74,
        passing: 81,
        dribbling: 80,
        defending: 78,
        physical: 84,
        composure: 82
      },
      {
        id: "ksa22-malki",
        name: "Abdulelah Al-Malki",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 79,
        pace: 74,
        shooting: 62,
        passing: 76,
        dribbling: 74,
        defending: 80,
        physical: 80,
        composure: 78
      },
      {
        id: "ksa22-faraj",
        name: "Salman Al-Faraj",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 80,
        pace: 71,
        shooting: 72,
        passing: 84,
        dribbling: 81,
        defending: 72,
        physical: 72,
        composure: 85
      },
      {
        id: "ksa22-abdulhamid",
        name: "Saud Abdulhamid",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 82,
        pace: 89,
        shooting: 60,
        passing: 77,
        dribbling: 80,
        defending: 81,
        physical: 82,
        composure: 80
      },
      {
        id: "ksa22-tambakti",
        name: "Hassan Al-Tambakti",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 81,
        shooting: 38,
        passing: 70,
        dribbling: 68,
        defending: 83,
        physical: 82,
        composure: 82,
        auraTrait: {
          id: "tambakti-tackle",
          name: "Lusail Goal-Line Block",
          description: "+35% last-man tackle success in penalty area.",
          shortDesc: "+35% last-man tackles",
          rarity: "Epic"
        }
      },
      {
        id: "ksa22-bulaihi",
        name: "Ali Al-Bulaihi",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 72,
        shooting: 44,
        passing: 69,
        dribbling: 64,
        defending: 83,
        physical: 86,
        composure: 83
      },
      {
        id: "ksa22-shahrani",
        name: "Yasser Al-Shahrani",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 80,
        pace: 83,
        shooting: 55,
        passing: 75,
        dribbling: 77,
        defending: 79,
        physical: 76,
        composure: 80
      },
      {
        id: "ksa22-buraikan",
        name: "Firas Al-Buraikan",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "FWD",
        specificPosition: "RW",
        overall: 78,
        pace: 82,
        shooting: 77,
        passing: 71,
        dribbling: 76,
        defending: 42,
        physical: 75,
        composure: 78
      },
      {
        id: "ksa22-owais",
        name: "Mohammed Al-Owais",
        clubYear: "Saudi Arabia 2022",
        clubName: "Saudi Arabia",
        year: "2022",
        country: "Saudi Arabia",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 85,
        pace: 60,
        shooting: 26,
        passing: 74,
        dribbling: 50,
        defending: 87,
        physical: 82,
        composure: 88,
        auraTrait: {
          id: "owais-lusail-wall",
          name: "The Green Wall of Lusail",
          description: "+30% reflex saves against shots on target when under heavy siege.",
          shortDesc: "+30% siege saves",
          rarity: "Epic"
        }
      }
    ]
  },

  // --- 15. Ghana 2010 (Black Stars African Pride) ---
  {
    id: "ghana-2010",
    clubName: "Ghana",
    year: "2010",
    fullName: "Ghana 2010 (World Cup Quarter-Finals)",
    type: "country",
    league: "International",
    countryCode: "GHA",
    badgeColor: "#FED100",
    accentColor: "#006B3F",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "gha10-gyan",
        name: "Asamoah Gyan",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 87,
        pace: 88,
        shooting: 87,
        passing: 76,
        dribbling: 85,
        defending: 42,
        physical: 84,
        composure: 85,
        auraTrait: {
          id: "gyan-baby-jet",
          name: "Baby Jet",
          description: "+30% shot power on breakaway strikes; top African scorer in World Cup history.",
          shortDesc: "+30% breakaway shot power",
          rarity: "Epic"
        }
      },
      {
        id: "gha10-boateng",
        name: "Kevin-Prince Boateng",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "MID",
        specificPosition: "CAM",
        overall: 85,
        pace: 82,
        shooting: 84,
        passing: 82,
        dribbling: 86,
        defending: 70,
        physical: 86,
        composure: 86
      },
      {
        id: "gha10-muntari",
        name: "Sulley Muntari",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 85,
        pace: 78,
        shooting: 86,
        passing: 84,
        dribbling: 81,
        defending: 78,
        physical: 85,
        composure: 85,
        auraTrait: {
          id: "muntari-cannon",
          name: "Soccer City Cannon",
          description: "+30% conversion on strikes from beyond 30 yards.",
          shortDesc: "+30% 30-yard long shots",
          rarity: "Epic"
        }
      },
      {
        id: "gha10-asamoah",
        name: "Kwadwo Asamoah",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "MID",
        specificPosition: "LM",
        overall: 84,
        pace: 84,
        shooting: 78,
        passing: 82,
        dribbling: 85,
        defending: 75,
        physical: 81,
        composure: 84
      },
      {
        id: "gha10-annan",
        name: "Anthony Annan",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "MID",
        specificPosition: "CDM",
        overall: 82,
        pace: 76,
        shooting: 64,
        passing: 79,
        dribbling: 77,
        defending: 84,
        physical: 82,
        composure: 81
      },
      {
        id: "gha10-tagoe",
        name: "Prince Tagoe",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "FWD",
        specificPosition: "RW",
        overall: 79,
        pace: 84,
        shooting: 76,
        passing: 71,
        dribbling: 78,
        defending: 40,
        physical: 76,
        composure: 78
      },
      {
        id: "gha10-mensah",
        name: "John Mensah",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 84,
        pace: 73,
        shooting: 40,
        passing: 70,
        dribbling: 66,
        defending: 86,
        physical: 88,
        composure: 85
      },
      {
        id: "gha10-vorsah",
        name: "Isaac Vorsah",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 81,
        pace: 72,
        shooting: 38,
        passing: 68,
        dribbling: 62,
        defending: 82,
        physical: 87,
        composure: 80
      },
      {
        id: "gha10-paintsil",
        name: "John Paintsil",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 81,
        pace: 82,
        shooting: 52,
        passing: 74,
        dribbling: 76,
        defending: 81,
        physical: 80,
        composure: 80
      },
      {
        id: "gha10-sarpei",
        name: "Hans Sarpei",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 80,
        pace: 80,
        shooting: 54,
        passing: 74,
        dribbling: 74,
        defending: 80,
        physical: 80,
        composure: 80
      },
      {
        id: "gha10-kingson",
        name: "Richard Kingson",
        clubYear: "Ghana 2010",
        clubName: "Ghana",
        year: "2010",
        country: "Ghana",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 83,
        pace: 56,
        shooting: 25,
        passing: 72,
        dribbling: 48,
        defending: 84,
        physical: 81,
        composure: 85
      }
    ]
  },

  // --- 16. England 2006 (The Golden Generation) ---
  {
    id: "england-2006",
    clubName: "England",
    year: "2006",
    fullName: "England 2006 (Golden Generation)",
    type: "country",
    league: "International",
    countryCode: "ENG",
    badgeColor: "#FFFFFF",
    accentColor: "#CE1124",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "eng06-rooney",
        name: "Wayne Rooney",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 91,
        pace: 89,
        shooting: 92,
        passing: 84,
        dribbling: 89,
        defending: 52,
        physical: 90,
        composure: 86,
        auraTrait: {
          id: "rooney-street-fighter",
          name: "Street Fighter",
          description: "+30% duel aggression and explosive long shot power; volatile temperament.",
          shortDesc: "+30% physical duel power",
          rarity: "Legendary"
        }
      },
      {
        id: "eng06-gerrard",
        name: "Steven Gerrard",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 91,
        pace: 83,
        shooting: 92,
        passing: 93,
        dribbling: 86,
        defending: 82,
        physical: 88,
        composure: 92,
        auraTrait: {
          id: "gerrard-screamer",
          name: "Hollywood Screamer",
          description: "+35% conversion on shots outside the penalty box.",
          shortDesc: "+35% long-range rocket xG",
          rarity: "Legendary"
        }
      },
      {
        id: "eng06-lampard",
        name: "Frank Lampard",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "MID",
        specificPosition: "CM",
        overall: 90,
        pace: 78,
        shooting: 93,
        passing: 89,
        dribbling: 84,
        defending: 76,
        physical: 84,
        composure: 92,
        auraTrait: {
          id: "lampard-late-run",
          name: "Ghost Into the Box",
          description: "+30% second-ball finishing on rebounds in the penalty box.",
          shortDesc: "+30% box rebound conversion",
          rarity: "Legendary"
        }
      },
      {
        id: "eng06-beckham",
        name: "David Beckham",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "MID",
        specificPosition: "RM",
        overall: 89,
        pace: 76,
        shooting: 88,
        passing: 96,
        dribbling: 84,
        defending: 74,
        physical: 82,
        composure: 94,
        auraTrait: {
          id: "beckham-whip",
          name: "Bend It Like Beckham",
          description: "+45% crossing and direct free-kick accuracy; scored winner vs Ecuador.",
          shortDesc: "+45% set-piece crossing",
          rarity: "Legendary"
        }
      },
      {
        id: "eng06-cole-j",
        name: "Joe Cole",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "MID",
        specificPosition: "LM",
        overall: 86,
        pace: 84,
        shooting: 82,
        passing: 85,
        dribbling: 90,
        defending: 50,
        physical: 72,
        composure: 86
      },
      {
        id: "eng06-owen",
        name: "Michael Owen",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "FWD",
        specificPosition: "ST",
        overall: 87,
        pace: 90,
        shooting: 89,
        passing: 75,
        dribbling: 86,
        defending: 35,
        physical: 72,
        composure: 89
      },
      {
        id: "eng06-terry",
        name: "John Terry",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 90,
        pace: 71,
        shooting: 55,
        passing: 78,
        dribbling: 68,
        defending: 93,
        physical: 90,
        composure: 94,
        auraTrait: {
          id: "terry-lionheart",
          name: "Lionheart Leader",
          description: "+30% blocked shots and defensive recovery duels.",
          shortDesc: "+30% shot blocks",
          rarity: "Epic"
        }
      },
      {
        id: "eng06-ferdinand",
        name: "Rio Ferdinand",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "DEF",
        specificPosition: "CB",
        overall: 90,
        pace: 82,
        shooting: 45,
        passing: 82,
        dribbling: 78,
        defending: 92,
        physical: 87,
        composure: 93
      },
      {
        id: "eng06-cole-a",
        name: "Ashley Cole",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "DEF",
        specificPosition: "LB",
        overall: 89,
        pace: 89,
        shooting: 62,
        passing: 82,
        dribbling: 84,
        defending: 89,
        physical: 81,
        composure: 89
      },
      {
        id: "eng06-neville",
        name: "Gary Neville",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "DEF",
        specificPosition: "RB",
        overall: 86,
        pace: 79,
        shooting: 55,
        passing: 84,
        dribbling: 76,
        defending: 87,
        physical: 82,
        composure: 88
      },
      {
        id: "eng06-robinson",
        name: "Paul Robinson",
        clubYear: "England 2006",
        clubName: "England",
        year: "2006",
        country: "England",
        league: "International",
        position: "GK",
        specificPosition: "GK",
        overall: 85,
        pace: 58,
        shooting: 30,
        passing: 76,
        dribbling: 50,
        defending: 86,
        physical: 83,
        composure: 85
      }
    ]
  }
];

// Combine and write
const mergedSquads = [...currentSquads, ...additionalSquads];
fs.writeFileSync(squadsJsonPath, JSON.stringify(mergedSquads, null, 2), 'utf8');

// Generate TypeScript file
const tsContent = `import { SquadData, GameMode } from '../types/football';

export const SQUADS: SquadData[] = ${JSON.stringify(mergedSquads, null, 2)};

export function getEligibleSquads(mode: GameMode, squads: SquadData[] = SQUADS): SquadData[] {
  if (mode === 'champions_league') {
    return squads.filter(s => s.type === 'club');
  }
  if (mode === 'world_cup') {
    return squads.filter(s => s.type === 'country');
  }
  if (
    mode === 'la_liga' ||
    mode === 'premier_league' ||
    mode === 'serie_a' ||
    mode === 'bundesliga' ||
    mode === 'invincible' ||
    mode === 'dynasty'
  ) {
    return squads.filter(s => s.type === 'club');
  }
  return squads;
}
`;

fs.writeFileSync(squadsTsPath, tsContent, 'utf8');
console.log(`Successfully appended 16 squads! Total squads: ${mergedSquads.length}`);
