const fs = require('fs');
const path = require('path');

const currentSquads = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/squads.json'), 'utf8'));

const batch2 = [
  {
    id: "valencia-2000-01",
    clubName: "Valencia",
    year: "2000-01",
    fullName: "Valencia 2000-01 (Cuper UCL Final)",
    type: "club",
    league: "La Liga",
    countryCode: "ESP",
    badgeColor: "#FFFFFF",
    accentColor: "#FF5500",
    primaryTactic: "Low-Block Counter",
    players: [
      {
        id: "val01-mendieta",
        name: "Gaizka Mendieta",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 91,
        pace: 82,
        shooting: 86,
        passing: 92,
        dribbling: 87,
        defending: 82,
        physical: 84,
        composure: 98,
        auraTrait: {
          id: "mendieta-penalty",
          name: "Unshakable Gaze",
          description: "+50% penalty conversion and composure under spotlight.",
          shortDesc: "+50% penalty accuracy",
          rarity: "Legendary"
        }
      },
      {
        id: "val01-aimar",
        name: "Pablo Aimar",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Argentina",
        league: "La Liga",
        position: "MID",
        specificPosition: "CAM",
        overall: 89,
        pace: 84,
        shooting: 81,
        passing: 91,
        dribbling: 94,
        defending: 45,
        physical: 66,
        composure: 92,
        auraTrait: {
          id: "el-payaso-magic",
          name: "El Payaso",
          description: "+35% tight space dribbles and slipped-in through balls.",
          shortDesc: "+35% through-ball xA",
          rarity: "Epic"
        }
      },
      {
        id: "val01-carew",
        name: "John Carew",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Norway",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 85,
        pace: 84,
        shooting: 85,
        passing: 70,
        dribbling: 78,
        defending: 40,
        physical: 92,
        composure: 83
      },
      {
        id: "val01-sanchez",
        name: "Juan Sanchez",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Spain",
        league: "La Liga",
        position: "FWD",
        specificPosition: "ST",
        overall: 84,
        pace: 83,
        shooting: 86,
        passing: 74,
        dribbling: 82,
        defending: 38,
        physical: 76,
        composure: 85
      },
      {
        id: "val01-kily-gonzalez",
        name: "Kily Gonzalez",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Argentina",
        league: "La Liga",
        position: "MID",
        specificPosition: "LM",
        overall: 87,
        pace: 88,
        shooting: 82,
        passing: 84,
        dribbling: 86,
        defending: 68,
        physical: 84,
        composure: 86
      },
      {
        id: "val01-baraja",
        name: "Ruben Baraja",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Spain",
        league: "La Liga",
        position: "MID",
        specificPosition: "CM",
        overall: 87,
        pace: 75,
        shooting: 84,
        passing: 88,
        dribbling: 82,
        defending: 84,
        physical: 86,
        composure: 88
      },
      {
        id: "val01-ayala",
        name: "Roberto Ayala",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Argentina",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 91,
        pace: 80,
        shooting: 45,
        passing: 72,
        dribbling: 68,
        defending: 94,
        physical: 90,
        composure: 94,
        auraTrait: {
          id: "el-raton-leap",
          name: "El Raton Aerial Dominance",
          description: "+40% aerial interception over taller strikers.",
          shortDesc: "+40% aerial clearance",
          rarity: "Legendary"
        }
      },
      {
        id: "val01-pellegrino",
        name: "Mauricio Pellegrino",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Argentina",
        league: "La Liga",
        position: "DEF",
        specificPosition: "CB",
        overall: 85,
        pace: 68,
        shooting: 38,
        passing: 70,
        dribbling: 62,
        defending: 88,
        physical: 87,
        composure: 84
      },
      {
        id: "val01-anglom",
        name: "Jocelyn Angloma",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "France",
        league: "La Liga",
        position: "DEF",
        specificPosition: "RB",
        overall: 85,
        pace: 82,
        shooting: 55,
        passing: 78,
        dribbling: 77,
        defending: 84,
        physical: 84,
        composure: 85
      },
      {
        id: "val01-carboni",
        name: "Amedeo Carboni",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Italy",
        league: "La Liga",
        position: "DEF",
        specificPosition: "LB",
        overall: 85,
        pace: 78,
        shooting: 50,
        passing: 76,
        dribbling: 75,
        defending: 87,
        physical: 85,
        composure: 87
      },
      {
        id: "val01-canizares",
        name: "Santiago Canizares",
        clubYear: "Valencia 2000-01",
        clubName: "Valencia",
        year: "2000-01",
        country: "Spain",
        league: "La Liga",
        position: "GK",
        specificPosition: "GK",
        overall: 91,
        pace: 60,
        shooting: 25,
        passing: 78,
        dribbling: 52,
        defending: 92,
        physical: 84,
        composure: 94
      }
    ]
  },
  {
    id: "liverpool-2004-05",
    clubName: "Liverpool",
    year: "2004-05",
    fullName: "Liverpool 2004-05 (Miracle of Istanbul)",
    type: "club",
    league: "Premier League",
    countryCode: "ENG",
    badgeColor: "#D00027",
    accentColor: "#F4B233",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "liv05-gerrard",
        name: "Steven Gerrard",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "England",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 93,
        pace: 84,
        shooting: 92,
        passing: 93,
        dribbling: 87,
        defending: 81,
        physical: 88,
        composure: 98,
        auraTrait: {
          id: "istanbul-captain-fury",
          name: "Hello, Hello, Here We Go",
          description: "+45% shot power and team stat boost when down by 2+ goals.",
          shortDesc: "+45% 3-goal deficit rally",
          rarity: "Legendary"
        }
      },
      {
        id: "liv05-xabi-alonso",
        name: "Xabi Alonso",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Spain",
        league: "Premier League",
        position: "MID",
        specificPosition: "CM",
        overall: 89,
        pace: 68,
        shooting: 80,
        passing: 95,
        dribbling: 82,
        defending: 82,
        physical: 81,
        composure: 93
      },
      {
        id: "liv05-baros",
        name: "Milan Baros",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Czech Republic",
        league: "Premier League",
        position: "FWD",
        specificPosition: "ST",
        overall: 84,
        pace: 88,
        shooting: 84,
        passing: 72,
        dribbling: 83,
        defending: 35,
        physical: 79,
        composure: 81
      },
      {
        id: "liv05-luis-garcia",
        name: "Luis Garcia",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Spain",
        league: "Premier League",
        position: "FWD",
        specificPosition: "RW",
        overall: 85,
        pace: 83,
        shooting: 85,
        passing: 82,
        dribbling: 87,
        defending: 40,
        physical: 68,
        composure: 87,
        auraTrait: {
          id: "ghost-goal-special",
          name: "Anfield Ghost Volley",
          description: "+35% decisive knockout goals from half-chances.",
          shortDesc: "+35% knockout volley",
          rarity: "Epic"
        }
      },
      {
        id: "liv05-kewell",
        name: "Harry Kewell",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Australia",
        league: "Premier League",
        position: "MID",
        specificPosition: "LM",
        overall: 84,
        pace: 84,
        shooting: 81,
        passing: 83,
        dribbling: 86,
        defending: 45,
        physical: 74,
        composure: 82
      },
      {
        id: "liv05-hamann",
        name: "Dietmar Hamann",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Germany",
        league: "Premier League",
        position: "MID",
        specificPosition: "CDM",
        overall: 85,
        pace: 64,
        shooting: 75,
        passing: 86,
        dribbling: 76,
        defending: 87,
        physical: 84,
        composure: 92
      },
      {
        id: "liv05-carragher",
        name: "Jamie Carragher",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "England",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 88,
        pace: 72,
        shooting: 35,
        passing: 70,
        dribbling: 60,
        defending: 92,
        physical: 88,
        composure: 94,
        auraTrait: {
          id: "cramping-tackle",
          name: "Cramp-Defying Block",
          description: "+40% goal-line clearances in extra time.",
          shortDesc: "+40% ET clearances",
          rarity: "Epic"
        }
      },
      {
        id: "liv05-hyypia",
        name: "Sami Hyypia",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Finland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "CB",
        overall: 88,
        pace: 66,
        shooting: 58,
        passing: 74,
        dribbling: 62,
        defending: 91,
        physical: 89,
        composure: 91
      },
      {
        id: "liv05-finnan",
        name: "Steve Finnan",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Ireland",
        league: "Premier League",
        position: "DEF",
        specificPosition: "RB",
        overall: 83,
        pace: 80,
        shooting: 50,
        passing: 78,
        dribbling: 76,
        defending: 83,
        physical: 79,
        composure: 83
      },
      {
        id: "liv05-traore",
        name: "Djimi Traore",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Mali",
        league: "Premier League",
        position: "DEF",
        specificPosition: "LB",
        overall: 80,
        pace: 79,
        shooting: 35,
        passing: 68,
        dribbling: 65,
        defending: 81,
        physical: 83,
        composure: 75
      },
      {
        id: "liv05-dudek",
        name: "Jerzy Dudek",
        clubYear: "Liverpool 2004-05",
        clubName: "Liverpool",
        year: "2004-05",
        country: "Poland",
        league: "Premier League",
        position: "GK",
        specificPosition: "GK",
        overall: 86,
        pace: 55,
        shooting: 20,
        passing: 72,
        dribbling: 50,
        defending: 88,
        physical: 82,
        composure: 94,
        auraTrait: {
          id: "spaghetti-legs",
          name: "Grobbelaar Spaghetti Legs",
          description: "+45% penalty shootout save probability against all opponents.",
          shortDesc: "+45% pen shootout mindgames",
          rarity: "Legendary"
        }
      }
    ]
  },
  {
    id: "inter-milan-1997-98",
    clubName: "Inter Milan",
    year: "1997-98",
    fullName: "Inter Milan 1997-98 (Ronaldo R9 Phenomenon)",
    type: "club",
    league: "Serie A",
    countryCode: "ITA",
    badgeColor: "#002F6C",
    accentColor: "#000000",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "int98-ronaldo",
        name: "Ronaldo Nazario",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Brazil",
        league: "Serie A",
        position: "FWD",
        specificPosition: "ST",
        overall: 97,
        pace: 98,
        shooting: 97,
        passing: 84,
        dribbling: 98,
        defending: 40,
        physical: 89,
        composure: 98,
        auraTrait: {
          id: "il-fenomeno-stepover",
          name: "Il Fenomeno",
          description: "+50% 1v1 conversion after beating goalkeeper with stepovers.",
          shortDesc: "+50% 1v1 stepover god",
          rarity: "Legendary"
        }
      },
      {
        id: "int98-djorkaeff",
        name: "Youri Djorkaeff",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "France",
        league: "Serie A",
        position: "MID",
        specificPosition: "CAM",
        overall: 90,
        pace: 82,
        shooting: 88,
        passing: 89,
        dribbling: 89,
        defending: 52,
        physical: 76,
        composure: 91
      },
      {
        id: "int98-zamorano",
        name: "Ivan Zamorano",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Chile",
        league: "Serie A",
        position: "FWD",
        specificPosition: "ST",
        overall: 87,
        pace: 82,
        shooting: 89,
        passing: 72,
        dribbling: 79,
        defending: 42,
        physical: 88,
        composure: 89,
        auraTrait: {
          id: "bam-bam-aerial",
          name: "Bam Bam 1+8 Header",
          description: "+40% heading accuracy from crosses.",
          shortDesc: "+40% aerial finish",
          rarity: "Epic"
        }
      },
      {
        id: "int98-simeone",
        name: "Diego Simeone",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Argentina",
        league: "Serie A",
        position: "MID",
        specificPosition: "CDM",
        overall: 88,
        pace: 76,
        shooting: 77,
        passing: 82,
        dribbling: 78,
        defending: 91,
        physical: 92,
        composure: 92,
        auraTrait: {
          id: "cholo-grit",
          name: "El Cholo Knife in Teeth",
          description: "+35% ground tackle win rate and intimidation of opposing playmaker.",
          shortDesc: "+35% enforcer tackle",
          rarity: "Legendary"
        }
      },
      {
        id: "int98-zanetti",
        name: "Javier Zanetti",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Argentina",
        league: "Serie A",
        position: "DEF",
        specificPosition: "RB",
        overall: 91,
        pace: 89,
        shooting: 68,
        passing: 84,
        dribbling: 88,
        defending: 90,
        physical: 88,
        composure: 96
      },
      {
        id: "int98-moriero",
        name: "Francesco Moriero",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Italy",
        league: "Serie A",
        position: "MID",
        specificPosition: "RM",
        overall: 84,
        pace: 86,
        shooting: 78,
        passing: 82,
        dribbling: 85,
        defending: 60,
        physical: 76,
        composure: 83
      },
      {
        id: "int98-winter",
        name: "Aron Winter",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Netherlands",
        league: "Serie A",
        position: "MID",
        specificPosition: "CM",
        overall: 85,
        pace: 75,
        shooting: 75,
        passing: 84,
        dribbling: 80,
        defending: 82,
        physical: 81,
        composure: 85
      },
      {
        id: "int98-bergomi",
        name: "Giuseppe Bergomi",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 89,
        pace: 72,
        shooting: 45,
        passing: 74,
        dribbling: 66,
        defending: 93,
        physical: 87,
        composure: 96
      },
      {
        id: "int98-galante",
        name: "Fabio Galante",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Italy",
        league: "Serie A",
        position: "DEF",
        specificPosition: "CB",
        overall: 82,
        pace: 72,
        shooting: 35,
        passing: 66,
        dribbling: 62,
        defending: 84,
        physical: 85,
        composure: 80
      },
      {
        id: "int98-taribo-west",
        name: "Taribo West",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Nigeria",
        league: "Serie A",
        position: "DEF",
        specificPosition: "LB",
        overall: 85,
        pace: 82,
        shooting: 40,
        passing: 68,
        dribbling: 70,
        defending: 87,
        physical: 91,
        composure: 82
      },
      {
        id: "int98-pagliuca",
        name: "Gianluca Pagliuca",
        clubYear: "Inter Milan 1997-98",
        clubName: "Inter Milan",
        year: "1997-98",
        country: "Italy",
        league: "Serie A",
        position: "GK",
        specificPosition: "GK",
        overall: 90,
        pace: 58,
        shooting: 24,
        passing: 75,
        dribbling: 50,
        defending: 91,
        physical: 85,
        composure: 92
      }
    ]
  },
  {
    id: "wolfsburg-2008-09",
    clubName: "Wolfsburg",
    year: "2008-09",
    fullName: "Wolfsburg 2008-09 (Grafite & Dzeko 54 Gls)",
    type: "club",
    league: "Bundesliga",
    countryCode: "GER",
    badgeColor: "#009900",
    accentColor: "#FFFFFF",
    primaryTactic: "Direct Vertical",
    players: [
      {
        id: "wol09-grafite",
        name: "Grafite",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Brazil",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 89,
        pace: 87,
        shooting: 92,
        passing: 74,
        dribbling: 86,
        defending: 38,
        physical: 90,
        composure: 90,
        auraTrait: {
          id: "backheel-bayern",
          name: "Backheel vs Bayern",
          description: "+45% solo dribble goal probability in title clashes.",
          shortDesc: "+45% big match solo goal",
          rarity: "Legendary"
        }
      },
      {
        id: "wol09-dzeko",
        name: "Edin Dzeko",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Bosnia and Herzegovina",
        league: "Bundesliga",
        position: "FWD",
        specificPosition: "ST",
        overall: 89,
        pace: 80,
        shooting: 92,
        passing: 79,
        dribbling: 83,
        defending: 40,
        physical: 89,
        composure: 91,
        auraTrait: {
          id: "bosnian-diamond",
          name: "Bosnian Diamond",
          description: "+35% header conversion and target-man knockdowns.",
          shortDesc: "+35% aerial goal",
          rarity: "Epic"
        }
      },
      {
        id: "wol09-misimovic",
        name: "Zvjezdan Misimovic",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Bosnia and Herzegovina",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CAM",
        overall: 88,
        pace: 72,
        shooting: 84,
        passing: 95,
        dribbling: 86,
        defending: 46,
        physical: 76,
        composure: 91,
        auraTrait: {
          id: "record-assists-20",
          name: "Record 20 Assists",
          description: "+45% through-ball accuracy to front two.",
          shortDesc: "+45% through-ball xA",
          rarity: "Legendary"
        }
      },
      {
        id: "wol09-gentner",
        name: "Christian Gentner",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Germany",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "LM",
        overall: 83,
        pace: 79,
        shooting: 77,
        passing: 81,
        dribbling: 80,
        defending: 76,
        physical: 82,
        composure: 82
      },
      {
        id: "wol09-josue",
        name: "Josue",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Brazil",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "CDM",
        overall: 85,
        pace: 74,
        shooting: 65,
        passing: 84,
        dribbling: 79,
        defending: 86,
        physical: 84,
        composure: 86
      },
      {
        id: "wol09-hasebe",
        name: "Makoto Hasebe",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Japan",
        league: "Bundesliga",
        position: "MID",
        specificPosition: "RM",
        overall: 82,
        pace: 76,
        shooting: 68,
        passing: 82,
        dribbling: 80,
        defending: 79,
        physical: 78,
        composure: 85
      },
      {
        id: "wol09-barzagli",
        name: "Andrea Barzagli",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Italy",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 86,
        pace: 72,
        shooting: 30,
        passing: 68,
        dribbling: 64,
        defending: 89,
        physical: 85,
        composure: 89
      },
      {
        id: "wol09-simunek",
        name: "Jan Simunek",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Czech Republic",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "CB",
        overall: 80,
        pace: 71,
        shooting: 30,
        passing: 64,
        dribbling: 60,
        defending: 82,
        physical: 82,
        composure: 78
      },
      {
        id: "wol09-rietzel",
        name: "Sascha Riether",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "RB",
        overall: 81,
        pace: 82,
        shooting: 55,
        passing: 75,
        dribbling: 76,
        defending: 80,
        physical: 80,
        composure: 79
      },
      {
        id: "wol09-schafer",
        name: "Marcel Schafer",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Germany",
        league: "Bundesliga",
        position: "DEF",
        specificPosition: "LB",
        overall: 83,
        pace: 84,
        shooting: 72,
        passing: 83,
        dribbling: 79,
        defending: 80,
        physical: 81,
        composure: 82
      },
      {
        id: "wol09-benaglio",
        name: "Diego Benaglio",
        clubYear: "Wolfsburg 2008-09",
        clubName: "Wolfsburg",
        year: "2008-09",
        country: "Switzerland",
        league: "Bundesliga",
        position: "GK",
        specificPosition: "GK",
        overall: 86,
        pace: 54,
        shooting: 20,
        passing: 74,
        dribbling: 48,
        defending: 87,
        physical: 83,
        composure: 87
      }
    ]
  }
];

const existingIds = new Set(currentSquads.map(s => s.id));
const combined = [...currentSquads];

for (const ns of batch2) {
  if (!existingIds.has(ns.id)) {
    combined.push(ns);
  }
}

const jsonOutput = JSON.stringify(combined, null, 2);
fs.writeFileSync(path.join(__dirname, '../src/data/squads.json'), jsonOutput, 'utf8');

const tsOutput = "import { SquadData } from '../types/football';\n\nexport const SQUADS: SquadData[] = " + jsonOutput + ";\n";
fs.writeFileSync(path.join(__dirname, '../src/data/squads.ts'), tsOutput, 'utf8');

console.log('Batch 2 added. Total squads now: ' + combined.length);
